### ISSUE TITLE
When can we use the tf lite  C++ support?

### ISSUE THREAD

**Issue by liusanchuan** [tensorflow/tflite-support#146]
thanks for your awesome work. and I'm very hungry to use the tf lite C++ in Android jni, but it seems haven't finished. did you have the time when we can use it?

**Comment by xunkai55** [comment]
If you only want to use the core TFLite with C++, please refer to: https://www.tensorflow.org/lite/api_docs/cc

TFLite Support projects & C++ is still in an early stage.

**Comment by lu-wang-g** [comment]
Closing the issue. Feel free to reopen it if you have other questions.
