### ISSUE TITLE
Which header files to include to run BERT qa task?

### ISSUE THREAD

**Issue by Mo-Abdelgawad** [tensorflow/tflite-support#181]
Hi, 

You provide an example of how to run BERT qa task [here](https://github.com/tensorflow/tflite-support/tree/master/tensorflow_lite_support/cc/task)

```
using tflite::task::text::qa::BertQuestionAnswerer;
using tflite::task::text::qa::QaAnswer;
// Create API handler with Mobile Bert model.
auto qa_client = BertQuestionAnswerer::CreateBertQuestionAnswererFromFile("/home/mohamed/tfLiteTransformers/lite-model_mobilebert_1_metadata_1.tflite", "/path/to/vocab");
// Or create API handler with Albert model.
// auto qa_client = BertQuestionAnswerer::CreateAlbertQuestionAnswererFromFile("/path/to/alBertModel", "/path/to/sentencePieceModel");


std::string context =
    "Nikola Tesla (Serbian Cyrillic: Никола Тесла; 10 "
    "July 1856 – 7 January 1943) was a Serbian American inventor, electrical "
    "engineer, mechanical engineer, physicist, and futurist best known for his "
    "contributions to the design of the modern alternating current (AC) "
    "electricity supply system.";
std::string question = "When was Nikola Tesla born?";
// Run inference with `context` and a given `question` to the context, and get top-k
// answers ranked by logits.
const std::vector<QaAnswer> answers = qa_client->Answer(context, question);
// Access QaAnswer results.
for (const QaAnswer& item : answers) {
  std::cout << absl::StrFormat("Text: %s logit=%f start=%d end=%d", item.text,
                               item.pos.logit, item.pos.start, item.pos.end)
            << std::endl;
}
// Output:
// Text: 10 July 1856 logit=16.8527 start=17 end=19
// ... (and more)
//
// So the top-1 answer is: "10 July 1856".
```

What are the header files that I should include so that it could run?
-----------------------------------------------------------------------------------------

-- When I include  `"tensorflow_lite_support/cc/task/text/qa/bert_question_answerer.h" `  I get the error: 
`class "std::unique_ptr<tflite::task::text::qa::QuestionAnswerer, std::default_delete<tflite::task::text::qa::QuestionAnswerer>>" has no member "Answer"`

-- When I add `"tensorflow_lite_support/cc/task/text/qa/bert_qa_c_api.h"` to solve the above error I got a different error:
`incomplete type is not allowed ` pointing to `"BertQuestionAnswerer::CreateBertQuestionAnswererFromFile"` 

Thanks, 
Mohamed

**Comment by Mo-Abdelgawad** [comment]
@xunkai55 could you help with that?

**Comment by lu-wang-g** [comment]
Sorry about the delay!

Please check out this demo for the usage of the C++ API: https://github.com/tensorflow/tflite-support/blob/master/tensorflow_lite_support/examples/task/text/desktop/bert_question_answerer_demo.cc

Feel free to let us know if you have other questions.
