### ISSUE TITLE
I could not able to capture the image on the fragments

### ISSUE THREAD

**Issue by vinodh2805** [tensorflow/tflite-support#226]
Hi I have integrated the tensor flow sdk in android, I want to capture the image from the camera with detector. How do i achieve this.
I have written the code on Camera Fragement, But it not works
Kindly give some suggestion.

**Comment by lu-wang-g** [comment]
Have you take a look at the [TFLite Object Detector reference app](https://github.com/tensorflow/examples/tree/master/lite/examples/object_detection/android)? [DetectorActivity](https://github.com/tensorflow/examples/blob/master/lite/examples/object_detection/android/app/src/main/java/org/tensorflow/lite/examples/detection/DetectorActivity.java) contains the code to process image from the camera, and then use detector to perform object detection.

**Comment by lu-wang-g** [comment]
Closing the issue. Feel free to reopen it if you have other questions.
