### ISSUE TITLE
TFLite runtime with select ops support in windows

### ISSUE THREAD

**Issue by pourfard** [tensorflow/tflite-support#237]
Hi,

I'm using a tflite model in android which runs without problem when I use "org.tensorflow:tensorflow-lite-select-tf-ops:0.0.0-nightly" because it contains some tensorflow operations (not completly tflite standard operations). In windows on the other hand, when I use the same model, I should install Tensorflow 2.4 as said in [this link](https://www.tensorflow.org/lite/guide/ops_select):

"Note: TensorFlow Lite with select TensorFlow ops are available in the TensorFlow pip package version since 2.3 for Linux and 2.4 for other environments."

My question is: Is there any way to use tflite model in windows using python language which supports select ops without installing complete Tensorflow 2.4 package?

**Comment by terryheo** [comment]
Could you share why you don't want to install TF 2.4 package?
We have TFLite only PIP distribution:  https://www.tensorflow.org/lite/guide/python, but you can't use TF ops with this package.

We have an experimental way to build TFLite PIP package with Flex delegate.
I haven't tested it on Windows, but you might be able to use this.
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/pip_package

Comparing this to TF 2.4 package, it's bit lighter but it's less preferable since you need to build the package.

```
bash CUSTOM_BAZEL_FLAGS=--define=tflite_pip_with_flex=true tensorflow/lite/tools/pip_package/build_pip_package_with_bazel.sh windows
```

**Comment by pourfard** [comment]
Thanks for quick reply.

Because its size is huge. TF 2.4 wheel file is about 400mb. I want to
deploy a small application for face detection. The model itself is about
1mb but I should embed whole TF package inside my application. I found
Tf-Nightly smaller than the main package. Its about 150mb but it still is
very large for the application. On android TFlite library with select ops
is about 23mb for each architecture (arm, x86,...) but I could not find any
small package for that in windows.

I think I should compile it from source code. But I still think it size
will not be less than tf-nightly?

**Comment by terryheo** [comment]
I see. The compiled wheel was less than 50MB. It could be worth to try.

**Comment by pourfard** [comment]
Sorry if I ask this question here. 

when i run this command :

`CUSTOM_BAZEL_FLAGS=--define=tflite_pip_with_flex=true tensorflow/lite/tools/pip_package/build_pip_package_with_bazel.sh windows`

there is an error:

```
ERROR: C:/porsapp/tensorflow/tensorflow/tensorflow/core/common_runtime/BUILD:1651:1: Illegal ambiguous match on configurable attribute "deps" in //tensorflow/core/common_runtime:core_cpu_internal:
//tensorflow:windows
//tensorflow:no_gcp_support
Multiple matches are not allowed unless one is unambiguously more specialized.
ERROR: Analysis of target '//tensorflow/lite/python/interpreter_wrapper:_pywrap_tensorflow_interpreter_wrapper' failed; build aborted:
```

but when i run this:

`tensorflow/lite/tools/pip_package/build_pip_package_with_bazel.sh`

there is no error.

I've checked out Tensorflow r.2.4. Do you know what the problem is?
