### ISSUE TITLE
Fitting tflite models

### ISSUE THREAD

**Issue by kthomas4031** [tensorflow/tflite-support#241]
Hello,

Is there any way to use something like the Keras "fit()" function using tflite? Currently, I am sending the data back to a server that is running the fit function, converting the model back to tflite, and sending it back to the Raspberry Pi. Is there a more efficient way to do this?

**Comment by ben-xD** [comment]
TensorFlow lite doesn't support training yet, so this isn't possible. However, they mentioned that this is coming in the future, but requires other features to come into place first, so don't hold your breath.
