### ISSUE TITLE
Converting model to tflite without optimization option

### ISSUE THREAD

**Issue by pjin257** [tensorflow/tflite-support#252]
I converted saved models to tflite without any optimization option. That's like,

`model = tf.keras.models.load_model('saved_model')`
`converter = tf.lite.TFLiteConverter.from_keras_model(model)`

I assumed above conversion is done under "default" optimization setting below:
`converter.optimizations = [tf.lite.Optimize.DEFAULT]`

However, I got a different result when I explicitly added the optimization option.
Converted tflite models got much smaller sizes with the option:
Without option: x1.02 ~ x3.84 smaller
With option: x4.08 ~ x11.999 smaller

It seems like quantization (32float -> 8int) is implemented only with the option since it made the models x4 times smaller.
Then what made the first conversion without option get smaller models?
Also, why one of the models didn't get so smaller? (only x1.02 smaller)

Thanks

System information

TensorFlow version (installed from source or binary): 2.3.0

Python version: 3.8.3

**Comment by lu-wang-g** [comment]
You're right. Quantization won'y apply if you don't explicitly set up the optimization option. 

And the tflite model (a [flatbuffers file](https://github.com/tensorflow/tensorflow/blob/bc295ed3bc729e94a0aa16214ae3c5a8b642858c/tensorflow/lite/schema/schema.fbs)) is in a different format of the [saved model](https://www.tensorflow.org/guide/saved_model). From the [Keras documentation](https://www.tensorflow.org/guide/keras/save_and_serialize):
"_A Keras model consists of multiple components:
1. An architecture, or configuration, which specifies what layers the model contain, and how they're connected.
2. A set of weights values (the "state of the model").
3. An optimizer (defined by compiling the model).
4. A set of losses and metrics (defined by compiling the model or calling add_loss() or add_metric())._"

And the tflite model strips off information about training (item 4) and compilation (item 3). Therefore the size will be smaller than Keras model.
