### ISSUE TITLE
Cannot find 'MetalDelegate' in scope

### ISSUE THREAD

**Issue by GeneralJing** [tensorflow/tflite-support#259]
When connecting the mobile phone to run the segmentation demo，It gives an error。
the code snippet：
#if targetEnvironment(simulator)
      // Use CPU for inference as MetalDelegate does not support iOS simulator.
      options = Interpreter.Options()
      options?.threadCount = 2
#else
      // Use GPU on real device for inference as this model is fully supported.
      delegates = [MetalDelegate()]
#endif

**Comment by lu-wang-g** [comment]
@khanhlvg do you have any idea why the MetalDelegate cannot be found?

**Comment by khanhlvg** [comment]
@GeneralJing  what was the error that you saw?

**Comment by GeneralJing** [comment]
delegates = [MetalDelegate()] this line， ‘MetalDelegate' cannot find. MetalDelegate()is undefined.

**Comment by adumrewal** [comment]
@GeneralJing as per the tflite documentation:

"From 2.4.0 version and latest nightly releases, by default GPU and Core ML delegates are excluded from the pod to reduce the binary size. You can include them by specifying subspec:
`pod 'TensorFlowLiteSwift', :subspecs => ['CoreML', 'Metal']`"

So you'll have to add 'Metal' to your podfile and only then will it be available.

**Comment by GeneralJing** [comment]
Thanks. I will try that later. Whatever result i have, i will leave a message here.

**Comment by GeneralJing** [comment]
I tried it and it worked. Thank you. But the time is very long on iphone 6s. 
Preprocessing:197ms
Model inference:56ms
Postprocessing:1591ms
Visualization:8ms.
How did you solve the time-consuming problem of tflite in practice？

**Comment by adumrewal** [comment]
Yeah I found it to be slow too. Didn't think it could be an issue with tflite implementation. I thought it must be related to model's size or something. I moved on from the model and am now looking for other alternatives.

**Comment by GeneralJing** [comment]
Ok, thanks for your help.

**Comment by adumrewal** [comment]
Hey @GeneralJing, just found this note in the tflite sample codes:
```
// Note: You may find postprocessing very slow if you run the sample app with Debug build.
// You will see significant speed up if you rerun using Release build, or change
// Optimization Level in the project's Build Settings to the same value with Release build.
```
Also checkout the following: 
https://blog.tensorflow.org/2020/07/accelerating-tensorflow-lite-xnnpack-integration.html

**Comment by GeneralJing** [comment]
I only tested the relevant time on my mobile phone and did not notice the relevant notes. Thank you for your carefulness and reminder. The added link is very valuable, and I will study it carefully. If I encounter other related problems later, can I communicate with you by email？

**Comment by adumrewal** [comment]
Haha yeah, same with me. Also, one more thing I noticed was that the post-processing codes were not optimised (atleast for my use-case) and do not utilise the gpu either. So that is also something you can look into if you want improved performance.

Yeah sure, feel free to reach out.
