### ISSUE TITLE
NameError: name 'ImageClassifierWriter' is not defined

### ISSUE THREAD

**Issue by danielbank** [tensorflow/tflite-support#278]
# Environment Info

- Python 3.7.3
- Tensorflow 1.15 built from source
- Pip versions:

```
tflite-support==0.1.0rc5
tflite-support-nightly==0.1.0.dev2020114
```

# Script

- Copied from [this stackoverflow question](https://stackoverflow.com/questions/64097085/issue-in-creating-tflite-model-populated-with-metadata-for-object-detection)

```
from tflite_support.metadata_writers import object_detector

ObjectDetectorWriter = object_detector.MetadataWriter
_MODEL_PATH = "./tflite/detect.tflite"
_LABEL_FILE = "./tflite/labelmap.txt"
_SAVE_TO_PATH = "./output/detect.tflite"

with open(_MODEL_PATH, "rb") as file:
  model_buffer = file.read()

writer = ImageClassifierWriter.create_for_inference(
    model_buffer, [127.5], [127.5], [_LABEL_FILE])
new_model = writer.populate()

with open(_SAVE_TO_PATH, "wb") as file:
  file.write(new_model)
```

I get the following error:

```
Traceback (most recent call last):
  File "./3_add_metadata_for_realz.py", line 11, in <module>
    writer = ImageClassifierWriter.create_for_inference(
NameError: name 'ImageClassifierWriter' is not defined
```

Please be gentle, I am a noob.

**Comment by anumac** [comment]
Hello! I had the same error as you, and it seems to be because of a typo in the stackoverflow snippet. Try changing 
`writer = ImageClassifierWriter.create_for_inference` to `writer = ObjectDetectorWriter.create_for_inference`.

**Comment by danielbank** [comment]
Thank you! @anumac
