### ISSUE TITLE
Publish to Maven Central or Google Maven

### ISSUE THREAD

**Issue by arturdryomov** [tensorflow/tflite-support#323]
Seems like TensorFlow Lite support and base artifacts are hosted on JCenter.

* [TensorFlow Lite](https://mvnrepository.com/artifact/org.tensorflow/tensorflow-lite?repo=bt-google-tensorflow)
* [TensorFlow Lite GPU](https://mvnrepository.com/artifact/org.tensorflow/tensorflow-lite-gpu)
* [TensorFlow Lite support](https://mvnrepository.com/artifact/org.tensorflow/tensorflow-lite-support)

The TensorFlow repo address at pages linked above is `https://dl.bintray.com/google/tensorflow/`.

JFrog announced [a full Bintray / JCenter shutdown](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/) on May 1st, 2021. It would be nice to have these artifacts available _somewhere_. While the title states Maven Central, it might be [the Google Maven repo](https://maven.google.com) if it’s more comfortable for Google folks.

**Comment by lu-wang-g** [comment]
Thanks for flagging the issue! We'll further investigate it!

@xunkai55 can you please align with the team and see how we should continue serving AAR targets?

**Comment by arturdryomov** [comment]
Might be related to tensorflow/tensorflow#46964.

**Comment by xunkai55** [comment]
Thanks @arturdryomov, exactly we're considering moving to another maven repo (possibly Google Maven or Maven Central).

**Comment by ac4391** [comment]
Hello,

Any news regarding this issue? I can't use my tflite model on Android studio anymore.

**Comment by ac4391** [comment]
Hi @xunkai55 ,

Thanks for reaching out so quickly.

Here is the error I receive when I try to use tensorflow lite :

![MicrosoftTeams-image (7)](https://user-images.githubusercontent.com/42954657/110809231-00c36a00-8285-11eb-9352-2b0dce3df6ee.png)

![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/42954657/110809321-1042b300-8285-11eb-8584-f11ac147fb84.png)

It worked fine until a few days ago so i suspect that it is due to the shut down of JCenter? Do you have a solution to propose?

**Comment by xunkai55** [comment]
The first image looks somehow compressed. Could you please paste a clearer version or the message directly? Thanks!

**Comment by arturdryomov** [comment]
Plain text would be great as well!

**Comment by ac4391** [comment]
Hi,

here is the error message :

FAILURE: Build failed with an exception.
 
* What went wrong:
Execution failed for task ':app:checkInterpreterDebugAarMetadata'.
> Could not resolve all files for configuration ':app:interpreterDebugRuntimeClasspath'.
   > Could not resolve org.tensorflow:tensorflow-lite:0.0.0-nightly-SNAPSHOT.
     Required by:
         project :app > project :lib_interpreter
      > Could not resolve org.tensorflow:tensorflow-lite:0.0.0-nightly-SNAPSHOT.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/org/tensorflow/tensorflow-lite/0.0.0-nightly-SNAPSHOT/maven-metadata.xml.
            > Could not HEAD 'https://jcenter.bintray.com/org/tensorflow/tensorflow-lite/0.0.0-nightly-SNAPSHOT/maven-metadata.xml'.
               > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
   > Could not resolve org.tensorflow:tensorflow-lite-metadata:0.0.0-nightly-SNAPSHOT.
     Required by:
         project :app > project :lib_interpreter
      > Could not resolve org.tensorflow:tensorflow-lite-metadata:0.0.0-nightly-SNAPSHOT.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/org/tensorflow/tensorflow-lite-metadata/0.0.0-nightly-SNAPSHOT/maven-metadata.xml.
            > Could not HEAD 'https://jcenter.bintray.com/org/tensorflow/tensorflow-lite-metadata/0.0.0-nightly-SNAPSHOT/maven-metadata.xml'.
               > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target


Thanks so much for replying.

**Comment by idstein** [comment]
Bintray will trigger from time to time service outages to remind everyone that this is before their service shutdown. See the shutdown roadmap on the referenced blog entry: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/.

Next scheduled brown out will be today Apr 12, 13:00-21:00 UTC, see https://status.bintray.com

**Comment by xunkai55** [comment]
We've already pushed artifacts to Maven Central. Closing it now. For any issues related, Feel free to reopen.
