### ISSUE TITLE
TFlite Variable output dimension

### ISSUE THREAD

**Issue by henry8th** [tensorflow/tflite-support#329]
Hello,
In the tflite java inference docs its mentioned that there is no straight forward way to interpreter.run a model with variable length outputs however support for this is a planned feature, is there a reference to the non straightforward way you could provide?
Would implementing the model via the C++ api be a better approach?
Many thanks

**Comment by lu-wang-g** [comment]
I think interpreter.run does support variable length outputs. It just you'll need to get the shape of the output through interpreter and then reallocate your output buffer each time.

**Comment by lu-wang-g** [comment]
I'll close this issue for now. Feel free to reopen if you have further questions.
