### ISSUE TITLE
Steps to build dynamic libraries of tflite for raspberry pi and aarch 64(armv8) boards

### ISSUE THREAD

**Issue by pranathibl** [tensorflow/tflite-support#333]
I have not found steps to build and generate dynamic tfLite library for these hardware devices. Could You provide me the steps to build dynamic .so for tfLite library.

**Comment by lu-wang-g** [comment]
Does this instruction help? https://www.tensorflow.org/lite/guide/build_rpi

**Comment by lu-wang-g** [comment]
I'll close this issue for now. Feel free to reopen if you have further questions.

**Comment by luca992** [comment]
How I built the metadata_extractor for mac
```
bazel build -c opt --cpu=darwin //tensorflow_lite_support/metadata/cc:metadata_extractor
```
rpi would probably be:

```
bazel build -c opt --cpu=elinux_armhf //tensorflow_lite_support/metadata/cc:metadata_extractor
```
or (depending on model)

```
bazel build -c opt --cpu=elinux_aarch64 //tensorflow_lite_support/metadata/cc:metadata_extractor
```
