### ISSUE TITLE
Kotlin support in future?

### ISSUE THREAD

**Issue by tuttelikz** [tensorflow/tflite-support#345]
Hi, just curious if support for kotlin is planned in the future?
Desirably, with some basic examples similar as described in [docs page](https://www.tensorflow.org/lite/inference_with_metadata/lite_support).
As of today, what is the best practice to integrate tflite-support for Kotlin project?
Thanks, find the lib useful :D

**Comment by lu-wang-g** [comment]
Kotlin support library is not prioritized at this moment. But I think we should create a few examples that utilizes the Support Liibrary in our Kotlin reference app.

@khanhlvg what do you think?

**Comment by khanhlvg** [comment]
The current support library is totally usable in Kotlin although our documentation only shows Java sample code.

@tuttelikz You can copy paste the Java sample code into a Kotlin class in Android Studio and the IDE will automatically convert the code to Kotlin for you if you choose to.
