### ISSUE TITLE
RESHAPE failed to prepare when invoking tf.signal.stft in tflite

### ISSUE THREAD

**Issue by pierremotard** [tensorflow/tflite-support#352]
I am building a flutter app that needs to record an audio and predict some label using a tflite model I built. For linking the audio recording and tflite I use the flutter plugin tf-lite audio (https://github.com/Caldarie/flutter_tflite_audio).

The tensorflow model works on colab but when I launch the app and inference happens hence when it calls interpreter.invoke(), the following error occurs: 
```
TensorFlow Lite Error: tensorflow/lite/kernels/reshape.cc:58 stretch_dim != -1 (0 != -1)
TensorFlow Lite Error: Node number 26 (RESHAPE) failed to prepare.
Failed to invoke the interpreter with error: Must call allocateTensors().
2
Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value: file tflite_audio/SwiftTfliteAudioPlugin.swift, line 290
* thread #2, queue = 'conversionQueue', stop reason = Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value
    frame #0: 0x00000001a672ee08 libswiftCore.dylib`_swift_runtime_on_report
libswiftCore.dylib`_swift_runtime_on_report:
->  0x1a672ee08 <+0>: ret
libswiftCore.dylib`_swift_reportToDebugger:
    0x1a672ee0c <+0>: b      0x1a672ee08               ; _swift_runtime_on_report
libswiftCore.dylib`_swift_shouldReportFatalErrorsToDebugger:
    0x1a672ee10 <+0>: adrp   x8, 341475
    0x1a672ee14 <+4>: ldrb   w0, [x8, #0x7c8]
Target 0: (Runner) stopped.
Lost connection to device.
```

Here is the tflite model I use.
[my_trivial_stft_model_1_input.tflite.zip](https://github.com/tensorflow/tflite-support/files/6028520/my_trivial_stft_model_1_input.tflite.zip)

On netron here is the problematic node:
![Screenshot 2021-02-23 at 12 16 18](https://user-images.githubusercontent.com/6213616/108836466-238d2780-75d1-11eb-9898-4bd1e2b07a93.png)

It looks like it is only squeezing the first dimension so maybe it cannot because as you can see on the following summary of my model the first dimension is None, I tried some tricks to avoid having this None but I am not familiar enough with tensorflow to be sure about the validity of the operations I am doing

![Screenshot 2021-02-23 at 12 18 34](https://user-images.githubusercontent.com/6213616/108836560-4586aa00-75d1-11eb-9bdc-3112f02bb5b1.png)

I have boiled down my model to the minimal size and this node is between these 2 lines of code, so I suspect the stft function to do this reshaping but have no idea.
 ```
spectrograms = tf.signal.stft(waveforms,
                                      frame_length=self.fft_size,
                                      frame_step=self.hop_size,
                                      pad_end=False)

        magnitude_spectrograms = tf.abs(spectrograms)
```

Can anyone help on this issue?
Thanks!

**Comment by jdduke** [comment]
Looping in @lu-wang-g and @renjie-liu to comment further.

**Comment by pierremotard** [comment]
Apparently  tf.signal.stft and tf.abs are not supported by tflite, so I had to implement them manually (tf.frame works though). 
It looks like all the Flex delegate (Flex.RFFT, Flex.Abs, ...) from tensorflow is not working on tflite.
Do you think it could be updated in the near future? For much better optimization. Thanks!

**Comment by lu-wang-g** [comment]
Looks like the issue is due to the invalid shape argument (second input, model_3/log_mel_spectrogram_2/stft/rfft2) to the Reshape op. The shape is [-1, -1, 513], however according to [reshape.cc](https://github.com/tensorflow/tensorflow/blob/fa5bbd6caeef9832f4b7126313a8980a4fe8b0f3/tensorflow/lite/kernels/reshape.cc#L58), at most one dimension of -1 is allowed. 

@pierremotard do you know if we can pass in a valid shape argument here?

**Comment by renjie-liu** [comment]
yes, can you fix the batch dimension? thanks!

**Comment by lu-wang-g** [comment]
Closing the issues since it goes stale. Feel free to reopen.
