### ISSUE TITLE
can not download sources in android by gradle

### ISSUE THREAD

**Issue by yuxiazff** [tensorflow/tflite-support#372]
I am runing the demo 'https://github.com/tensorflow/examples/tree/master/lite/examples/text_classification/android' in android. When i try to download the source of 'tensorflow-lite-task-text-0.0.0-nightly@arr' with gradle,  i got the error as follows:

`16:39:51: Executing task 'DownloadSources --info'...

Executing tasks: [DownloadSources] in project D:\androidstudioprogram\examples\lite\examples\text_classification\android

The client will now receive all logging from the daemon (pid: 14264). The daemon log file: C:\Users\DELL\.gradle\daemon\6.1.1\daemon-14264.out.log
Starting 7th build in daemon [uptime: 1 hrs 30 mins 29.813 secs, performance: 100%]
Closing daemon's stdin at end of input.
The daemon will no longer process any standard input.
Using 4 worker leases.
Starting Build
Settings evaluated using settings file 'D:\androidstudioprogram\examples\lite\examples\text_classification\android\settings.gradle'.
Projects loaded. Root project using build file 'D:\androidstudioprogram\examples\lite\examples\text_classification\android\build.gradle'.
Included projects: [root project 'TFLite Text Classification Demo App', project ':app', project ':lib_interpreter', project ':lib_task_api']

> Configure project :
Evaluating root project 'TFLite Text Classification Demo App' using build file 'D:\androidstudioprogram\examples\lite\examples\text_classification\android\build.gradle'.
Invalidating in-memory cache of C:\Users\DELL\.gradle\caches\journal-1\file-access.bin
Invalidating in-memory cache of C:\Users\DELL\.gradle\caches\6.1.1\fileHashes\fileHashes.bin
Invalidating in-memory cache of C:\Users\DELL\.gradle\caches\6.1.1\fileHashes\resourceHashesCache.bin

> Configure project :app
Evaluating project ':app' using build file 'D:\androidstudioprogram\examples\lite\examples\text_classification\android\app\build.gradle'.
Creating configuration androidTestUtil

> Configure project :lib_interpreter
Evaluating project ':lib_interpreter' using build file 'D:\androidstudioprogram\examples\lite\examples\text_classification\android\lib_interpreter\build.gradle'.
Creating configuration androidTestUtil

> Configure project :lib_task_api
Evaluating project ':lib_task_api' using build file 'D:\androidstudioprogram\examples\lite\examples\text_classification\android\lib_task_api\build.gradle'.
Creating configuration androidTestUtil
All projects evaluated.
Analytics other plugin to proto: Unknown plugin type de.undercouch.gradle.tasks.download.DownloadTaskPlugin expected enum DE_UNDERCOUCH_GRADLE_TASKS_DOWNLOAD_DOWNLOADTASKPLUGIN
Analytics other plugin to proto: Unknown plugin type de.undercouch.gradle.tasks.download.DownloadTaskPlugin expected enum DE_UNDERCOUCH_GRADLE_TASKS_DOWNLOAD_DOWNLOADTASKPLUGIN
Selected primary task 'DownloadSources' from project :
Tasks to be executed: [task ':lib_task_api:DownloadSources']
:lib_task_api:DownloadSources (Thread[Daemon worker Thread 5,5,main]) started.

> Task :lib_task_api:DownloadSources FAILED
Task :lib_task_api:DownloadSources in app Starting
Caching disabled for task ':lib_task_api:DownloadSources' because:
  Build cache is disabled
Task ':lib_task_api:DownloadSources' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
Resource missing. [HTTP HEAD: https://dl.google.com/dl/android/maven2/org/tensorflow/tensorflow-lite-task-text/0.0.0-nightly@aar/tensorflow-lite-task-text-0.0.0-nightly@aar.pom]
Resource missing. [HTTP HEAD: https://jcenter.bintray.com/org/tensorflow/tensorflow-lite-task-text/0.0.0-nightly@aar/tensorflow-lite-task-text-0.0.0-nightly@aar.pom]
Task :lib_task_api:DownloadSources in app Finished
:lib_task_api:DownloadSources (Thread[Daemon worker Thread 5,5,main]) completed. Took 0.824 secs.
1 actionable task: 1 executed

FAILURE: Build failed with an exception.

* Where:
Initialization script 'C:\Users\DELL\AppData\Local\Temp\ijmiscinit1.gradle' line: 20

* What went wrong:
Execution failed for task ':lib_task_api:DownloadSources'.
> Could not resolve all files for configuration ':lib_task_api:downloadSources_6a4637ed-031b-43a8-a402-10ca98ba8740'.
   > Could not find org.tensorflow:tensorflow-lite-task-text:0.0.0-nightly@aar.
     Required by:
         project :lib_task_api

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
16:39:53: Task execution finished 'DownloadSources --info'.
`

**Comment by lu-wang-g** [comment]
The nightly build was broken, and we've created a new target ['org.tensorflow:tensorflow-lite-task-text:0.0.0-nightly-SNAPSHOT'](https://bintray.com/google/tensorflow/tensorflow-lite-task-text/0.0.0-nightly-SNAPSHOT). You can also use the 0.1 version. See [here](https://github.com/tensorflow/examples/blob/e6e7388f90c6450edc9eda7bf9d293a79cbef6cc/lite/examples/text_classification/android/lib_task_api/build.gradle#L39)

**Comment by lu-wang-g** [comment]
Closing the issue. Let us know if you have other questions. Thanks!
