### ISSUE TITLE
TFLite Support Codegen Tool: Quantized models don't output probabilities

### ISSUE THREAD

**Issue by ben-xD** [tensorflow/tflite-support#451]
I am trying to understand why the denormalised (or dequantized) output from my quantized model does not lie between 0 and 1, as they **should be probabilities**. Instead, they are sometimes negative float numbers, and sometimes numbers larger than 10.

I used the TFLite support codegen tool to generate the class, so I did not mess with this class. I have also found that MLKit, TFLite task library do not provide **probabilities** (numbers between 0 and 1).

Here's what I found:
1. Probabilities are not 0. See [here](https://i.imgur.com/J3TvXAJ.png)
2. I discovered that this is being calculated by the `probabilityPostprocessor: TensorProcessor`
3. This is set by `fun resetProbabilityPostprocessor`
4. This setter is passed the following as argument `instance.buildDefaultProbabilityPostprocessor()`
5. The code in `buildDefaultProbabilityPostprocessor` is:
```kotlin
    private fun buildDefaultProbabilityPostprocessor(): TensorProcessor {
        return TensorProcessor.Builder()
                .add(DequantizeOp(
                        metadata.probabilityQuantizationParams.zeroPoint.toFloat(),
                        metadata.probabilityQuantizationParams.scale))
                .build()
    }
```
6. The zeroPoint and scale values are taken from `probabilityQuantizationParams`
7. `probabilityQuantizationParams` is set with `probabilityTensor.quantizationParams()`
8. And finally, `val probabilityTensor = model.getOutputTensor(0)`. 

The last step, **step 8 seems incorrect**? Finally, I discovered that the quantization (and also dequantization) parameters are taken from the **output tensor** of the model. _What does this mean?_ How does getting the output tensor of a model (trained or untrained) provide any information about quantization?

Thank you, :)

**Comment by ben-xD** [comment]
Oh, I understand what it is doing: The output tensor has a property inside it which keeps track of the quantization it had. And this is not a code error, but a model issue. My input image could be causing wildly different probabilities because the model has not seen it before.

**Comment by lu-wang-g** [comment]
No problem. Let us know if you have further questions.
