### ISSUE TITLE
Does tflite support tensorflow probability?

### ISSUE THREAD

**Issue by maxkaustav** [tensorflow/tflite-support#453]
I have a Tensorflow probability model can it be converted into tflite format

**Comment by lu-wang-g** [comment]
TFLite is able to convert most TF models. Can you please first try convert your model according to our [public documentation](https://www.tensorflow.org/lite/convert)? Let us know if you run into any issue.

**Comment by lu-wang-g** [comment]
Closing the issue. Feel free to reopen.
