### ISSUE TITLE
Null is not an object evaluating (TfliteReactNative.loadModel)

### ISSUE THREAD

**Issue by XamarinPOC** [tensorflow/tflite-support#47]
dependencies": { "react": "16.13.1", "react-native": "0.63.0", "react-native-image-picker": "^2.3.2", "tflite-react-native": "0.0.5"
target 'TFDemo' do
pod 'TensorFlowLite', '1.12.0'
config = use_native_modules!

/**

Metro configuration for React Native
https://github.com/facebook/react-native
@Format
*/
module.exports = {
resolver: {
assetExts: ['tflite', 'txt']
<img width="341" alt="Screenshot 2020-07-13 at 12 03 51 PM" src="https://user-images.githubusercontent.com/34939819/87396352-551c2a00-c5d0-11ea-87f6-0e0e4b78be20.png">

}
}
Hey Folks ,
I'm facing this issue . Is this a bug or i'm missing any things

**Comment by xunkai55** [comment]
Hi @XamarinPOC , I think you're not asking in the right place. The "tflite-react-native" library is not in this repo.
