### ISSUE TITLE
Pre-process input for InceptionV3 tflite model

### ISSUE THREAD

**Issue by clgilbe** [tensorflow/tflite-support#490]
I have successfully converted an InceptionV3 model to tflite using toco and inference type FLOAT.  I have verified that the tflite model will produce good classification confidence levels as long as the image input data is pre-processed the exact same way as the input to the .pb model.  I verified this by extracting the preprocessed data on .NET and running the exact same input on the tflite model in Android. 

The problem I'm having is formatting the image input using tflite on Android to get the same classification confidence levels.  Here is the method used to preprocess data with SciSharp https://github.com/SciSharp/SciSharp-Stack-Examples/blob/master/src/TensorFlowNET.Examples/ImageProcessing/TransferLearningWithInceptionV3.cs
```
        private (Tensor, Tensor) add_jpeg_decoding()
        {
            // height, width, depth
            var input_dim = (299, 299, 3);
            var jpeg_data = tf.placeholder(tf.@string, name: "DecodeJPGInput");
            var decoded_image = tf.image.decode_jpeg(jpeg_data, channels: input_dim.Item3);
            // Convert from full range of uint8 to range [0,1] of float32.
            var decoded_image_as_float = tf.image.convert_image_dtype(decoded_image, tf.float32);
            var decoded_image_4d = tf.expand_dims(decoded_image_as_float, 0);
            var resize_shape = tf.stack(new int[] { input_dim.Item1, input_dim.Item2 });
            var resize_shape_as_int = tf.cast(resize_shape, dtype: tf.int32);
            var resized_image = tf.image.resize_bilinear(decoded_image_4d, resize_shape_as_int);
            return (jpeg_data, resized_image);
        }
```

I can replicate the image pre processing up to the tf.expand_dims line.  Is there a way to effectively do all of this preprocessing in Android using tflite-support?  These are the commands I'm having trouble replicating:
```
            var decoded_image_4d = tf.expand_dims(decoded_image_as_float, 0);
            var resize_shape = tf.stack(new int[] { input_dim.Item1, input_dim.Item2 });
            var resize_shape_as_int = tf.cast(resize_shape, dtype: tf.int32);
            var resized_image = tf.image.resize_bilinear(decoded_image_4d, resize_shape_as_int);
```
I understand there is ImageProcessor with a ResizeOp, but that does not give me the same results as the processing the image in .NET with the above commands.  Is there a way to replicate the above 4 lines using tflite-support methods?

**Comment by lu-wang-g** [comment]
Can you please give a code snippet of how you used ImageProcessor with ResizeOp as well as the results of ResizeOp and resize_bilinear respectively?

**Comment by clgilbe** [comment]
Closing this issue as we used tflite-model-maker to train the InceptionV3 model for Android
