### ISSUE TITLE
Evaluating Imagenet accuracy of TF Lite models 

### ISSUE THREAD

**Issue by lcmeng** [tensorflow/tflite-support#539]
Hi,

I used the official Imagenet accuracy evaluation tool at tensorflow/tensorflow/lite/tools/evaluation/tasks/imagenet_image_classification/ on the official quantized MobileNet V2. However, the reported accuracy is far below the expected. The MB V2 is downloaded from https://tfhub.dev/tensorflow/lite-model/mobilenet_v2_1.0_224_quantized/1/default/1. The run settings below have followed the [instructions](https://github.com/tensorflow/tensorflow/blob/5dcfc51118817f27fad5246812d83e5dccdc5f72/tensorflow/lite/tools/evaluation/tasks/imagenet_image_classification/README.md) as much as possible. Please help explain the accuracy gap.

Command:
```
bazel run -c opt \
-- \
//tensorflow/lite/tools/evaluation/tasks/imagenet_image_classification:run_eval \
--model_file=/home/ubuntu/workspace/tensorflow/mobilenet_v2_1.0_224_quantized_1_default_1.tflite \
--ground_truth_images_path=${IMAGENET_IMAGES_DIR} \
--ground_truth_labels=${VALIDATION_LABELS} \
--model_output_labels=${MODEL_LABELS_TXT_LONG} \
--output_file_path=/tmp/accuracy_output.txt \
--num_interpreter_threads=4 \
--num_images=0
```
Output:
```
Num evaluation runs: 50000
Preprocessing latency: avg=7697.15(us), std_dev=0(us)
Inference latency: avg=77301.9(us), std_dev=6485(us)
Top-1 Accuracy: 0.35942
Top-2 Accuracy: 0.41372
Top-3 Accuracy: 0.43532
Top-4 Accuracy: 0.4475
Top-5 Accuracy: 0.4553
Top-6 Accuracy: 0.46088
Top-7 Accuracy: 0.46498
Top-8 Accuracy: 0.46842
Top-9 Accuracy: 0.47142
Top-10 Accuracy: 0.4736
```

**Comment by wangtz** [comment]
Hi LC,

It seems that the issue you reported is not related to tflite_support, rather a TFLite issue. Do you want to raise the issue in http://github.com/tensorflow/tensorflow ?

Thanks,
Tiezhen

**Comment by lu-wang-g** [comment]
Maybe @multiverse-tf can help us take a look at this issue.

**Comment by multiverse-tf** [comment]
> Hi LC,
> 
> It seems that the issue you reported is not related to tflite_support, rather a TFLite issue. Do you want to raise the issue in [http://github.com/tensorflow/tensorflow](https://github.com/tensorflow/tensorflow) ?

+1.

> 
> Thanks,
> Tiezhen

And regarding the accuracy, what're the values if only the first 300 images are evaluated? Thx!

**Comment by lu-wang-g** [comment]
Closing the issue. Feel free to reopen.
