### ISSUE TITLE
image_embedder demo is missing model

### ISSUE THREAD

**Issue by aakbar5** [tensorflow/tflite-support#563]
image_embedder demo is missing instructions to download model and its model can't be found on tfhub as well.

**Comment by lu-wang-g** [comment]
Thanks for the feedback! We'll add instructions when ImageEmbedder is fully released. If you are interested, try out this [embedder model on TFHub](https://tfhub.dev/google/imagenet/mobilenet_v3_large_100_224/feature_vector/5).

**Comment by lu-wang-g** [comment]
Closing the issue. Feel free to reopen.
