### ISSUE TITLE
Calculate Gradient w.r.t input for quantized tflite model

### ISSUE THREAD

**Issue by WeiHao97** [tensorflow/tflite-support#566]
Hi, I am trying to calculate Gradient w.r.t input for quantized tflite model. But I noticed that there is no training path in tflite so I am re-constructing a regular tensorflow model who shares the same architecture and weight from the tflite model but only in floating point format. During the reconstruction, I am wondering how is the input quantization handled by tflite. If the input is a single image, does tflite use the min and max values in this image for input quantization? also, how is integer overflow handled by tflite? for example, if the resulting activation values of certain kernel exceeds -127-127, does tflite do quantization again in the activation layer so that the numbers at the activation layer stays within -127-127 for int8 quantization?
Thank you!

**Comment by lu-wang-g** [comment]
@liyunlu0618 Can you please comment on the questions about quantization above? Thanks!

**Comment by WeiHao97** [comment]
@liyunlu0618 @lu-wang-g
Any updates? Thanks!
