### ISSUE TITLE
i have 3 tflite and some python code that connects tham together.how do i integerate them with android

### ISSUE THREAD

**Issue by Aryan-Solanki** [tensorflow/tflite-support#567]
![image](https://user-images.githubusercontent.com/37494973/122703239-bcc20700-d26e-11eb-9156-481c839ae4e5.png)

 there are multiple python files and i want to integerate it with flutter do i have to change my python code to dart???

**Comment by lu-wang-g** [comment]
@wangtz any suggestions for flutter integration?

**Comment by wangtz** [comment]
Hi Aryan,

From file name (augmentation) it looks like the python file is for training so irrelevant to deployment. Task library helps you easily deploy the TFLite file on mobile. 

We don't have official task library support for Flutter, you might want to try https://pub.dev/packages/tflite for now.

**Comment by lu-wang-g** [comment]
Closing the issue. Feel free to reopen.
