### ISSUE TITLE
ResizeWithCropOrPadOp does not have functionality of cropping with bounding boxes, works only with center crop.

### ISSUE THREAD

**Issue by sharmadev2506** [tensorflow/tflite-support#576]
Hi, I have a requirement where I have to crop and resize an image with imageProcessor. The ResizeWithCropOrPadOp does only centre cropping and does not work with coordinates. Can anybody suggest anything?

**Comment by lu-wang-g** [comment]
Loop in @xunkai55 to take a look at this issue.

**Comment by xunkai55** [comment]
Sorry, currently we don't provide APIs to crop a with bounding box.

**Comment by sharmadev2506** [comment]
Okay. Thanks
