### ISSUE TITLE
Support for Pose Estimation

### ISSUE THREAD

**Issue by jonpsy** [tensorflow/tflite-support#587]
Hello all,

I've tried applying for this organization to implement Pose Estimation Task to the library. Regardless of my selection, I wish to contribute to this. @MeghnaNatraj  I believe you're the project lead for this (correct me if I'm wrong), I think the project details were to be shared when selected, but since nobody has taken it up would you mind sharing it with me? I'll try my best to implement it. I have sufficient experience in C++ and ML to tackle this, and I've drawn up some ideas on how to do this is as well. Looking forward to hearing from the team.

**Comment by lu-wang-g** [comment]
@jonpsy thanks for reaching out. The position for the pose estimation API has been filled. And I don't think we can still accept new GSoC projects. Let me know if you are interested in working on other projects of the support library repo. You're more than welcome to contribute.

**Comment by jonpsy** [comment]
@lu-wang-g Sure I would love to. I'd be interested on Vision Based Task mostly. How do i go about it?

**Comment by lu-wang-g** [comment]
Model training is not in the scope of this repo, but if you are interested, I can help to refer you to the specific team member. 

> How do I go about it?
Since this will not be a formal program like GSoC, depending on your interest and availability, you can let us know any specific area/project you'd like to work on or improve. Or you can contribute to projects in our prioritized list, such as Task library Python API, metadata CLI tool, new tasks, new utils in the support library, etc.

**Comment by jonpsy** [comment]
Thanks for the details. My interest mostly lies in inference on edge devices. In fact, as part of a project, I wrapped the ```TFLiteInterpreter``` functionalities around a simple user interface and used delegates to enhance performance, which is why I like this library because it does something very similar. 

I'd be interested on tackling a new task. Currently my interest lies in Re-inforcement learning, so if you guys have any task library ideas around it that'd be great. Else, I can work on Vision Based tasks as well.

**Comment by lu-wang-g** [comment]
Thanks for sharing your ideas with us! 

Loop in @lintian06 to see if there are any opportunities for reinforcement learning in TFLite Model Maker.

For Task library related projects, will you be interested in developing new vision tasks, like super resolution, style transfer, and image text recognition?

**Comment by jonpsy** [comment]
Honestly, all of this ideas are equally awesome! The one that piques my interest is the Super resolution task. I'd love to get started on it (assuming the reinforcement learning task isn't available).  Thanks for the response!

**Comment by lu-wang-g** [comment]
Sounds great! Please email to tflite-support-team@google.com, and we can discuss further from there.
