### ISSUE TITLE
python quickstart guide doesn't mention how to use python 3.8

### ISSUE THREAD

**Issue by aguaviva** [tensorflow/tflite-support#60]
Thanks for the great documentation though.

**Comment by lu-wang-g** [comment]
Which python quickstart guide do you refer to?

**Comment by aguaviva** [comment]
this one: https://www.tensorflow.org/lite/guide/python

**Comment by lu-wang-g** [comment]
Thanks for flagging the issue! I've created a bug internally to track it. However, for general TFlite issue like this, it will be more efficient to create an issue in the TF/TFlite github repo: https://github.com/tensorflow/tensorflow.

**Comment by lu-wang-g** [comment]
The instruction for windows 10 has been added. Closing this issue. Feel free to reopen it if you have other questions.
