### ISSUE TITLE
TransformToGrayscaleOp

### ISSUE THREAD

**Issue by jcgeo9** [tensorflow/tflite-support#604]
Hello, I am having an issue with transformation to grayscale. I am using the following line:

        ImageProcessor imageProcessor =
                new ImageProcessor.Builder()
                        .add(new ResizeWithCropOrPadOp(cropSize, cropSize))
                        .add(new ResizeOp(imageSizeX, imageSizeY, ResizeOp.ResizeMethod.NEAREST_NEIGHBOR))
                        .add(new  TransformToGrayscaleOp())
                        .add(getPreprocessNormalizeOp())
                        .build();

The problem is: Cannot resolve symbol 'TransformToGrayscaleOp'

I checked the github repo and its an image operator just like ResizeOp and ResizeWithCropOrPadOp but it seems that it cannot be imported. 

What am I doing wrong?

**Comment by lu-wang-g** [comment]
TransformToGrayscaleOp should be only available in the following two versions:
nightly build: org.tensorflow:tensorflow-lite-support:0.0.0-nightly-SNAPSHOT
0.2.0: org.tensorflow:tensorflow-lite-support:0.2.0

Are you using the one of the above two?

**Comment by jcgeo9** [comment]
i was using nightly it i could not import it. Then i switched to 0.2.0 and it worked fine. thank you
