### ISSUE TITLE
Could not find org.tensorflow:tensorflow-lite-support:0.1.0-rc1

### ISSUE THREAD

**Issue by yuyecreus** [tensorflow/tflite-support#616]
Hello everybody :)

I am converting a transformer model for text classification to TFLite. Conversion works. When I integrate it in the Android Studio template for text classification ([https://www.tensorflow.org/lite/examples/text_classification/overview](url)) I use lib_interpreter and obtain the following error:

Execution failed for task ':app:checkInterpreterDebugAarMetadata'.
> Could not resolve all files for configuration ':app:interpreterDebugRuntimeClasspath'.
   > Could not find org.tensorflow:tensorflow-lite-support:0.1.0-rc1.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/org/tensorflow/tensorflow-lite-support/0.1.0-rc1/tensorflow-lite-support-0.1.0-rc1.pom
       - https://repo.maven.apache.org/maven2/org/tensorflow/tensorflow-lite-support/0.1.0-rc1/tensorflow-lite-support-0.1.0-rc1.pom
       - http://oss.sonatype.org/content/repositories/snapshots/org/tensorflow/tensorflow-lite-support/0.1.0-rc1/tensorflow-lite-support-0.1.0-rc1.pom
     Required by:
         project :app > project :lib_interpreter

What is going on here? Thank you very much!

**Comment by xunkai55** [comment]
0.1.0-rc1 was on Bintray/Jcenter, which is already sunset.

Could you please try 0.2.0 instead? Thanks!

**Comment by yuyecreus** [comment]
> 0.1.0-rc1 was on Bintray/Jcenter, which is already sunset.
> 
> Could you please try 0.2.0 instead? Thanks!

Perfect! Changing to 0.2.0 works!
