### ISSUE TITLE
TFlite model inference in Android Studio

### ISSUE THREAD

**Issue by yuyecreus** [tensorflow/tflite-support#617]
Hello everybody,

I am importing a CNN in Android Studio and now want to do inference on new images in an Android Device.

I load my labels from a text file:

`val labels = application.assets.open("labels.txt").bufferedReader().use { it.readText() }.split("\n")`

I get the bitmap of the selected image:

```
bitmap = MediaStore.Images.Media.getBitmap(this.contentResolver, uri)
var resized = Bitmap.createScaledBitmap(bitmap, 256, 256, true)
```

I instantiate the mode (which is in the float32 type, not-quantizedl:

`val model = Model.newInstance(this)`

Define a byte buffer for it:

```
var byteBuffer = ByteBuffer.allocate(256 * 256 * 1 * 3 * 4)
resized.copyPixelsToBuffer(byteBuffer)
```

Define the inputs and outputs:

```
val inputFeature0 = TensorBuffer.createFixedSize(intArrayOf(1, 256, 256, 3), DataType.FLOAT32)
inputFeature0.loadBuffer(byteBuffer)

val outputs = model.process(inputFeature0)
val outputFeature0 = outputs.outputFeature0AsTensorBuffer
```

and just retrieve the max of `outputFeature0.floatArray`

The problem is I am always obtaining the first label as the predicted class. I don't really know where I am making the error. 

Thank you very much!

**Comment by xunkai55** [comment]
`Bitmap#copyPixelsToBuffer` if I remember correctly copies RGBA data (4 channels). Wouldn't it throw an overflow error?

**Comment by yuyecreus** [comment]
> `Bitmap#copyPixelsToBuffer` if I remember correctly copies RGBA data (4 channels). Wouldn't it throw an overflow error?

I think my app loads an image from the media storage as RGB so ByteBuffer.allocate(256 * 256 * 1  * 4) is enough but then the model expects a TensorBuffer.createFixedSize(intArrayOf(1, 256, 256, 3), DataType.FLOAT32). Any way I can't remove the A channel and just obtain the RGB image?

**Comment by xunkai55** [comment]
You can try to use our `TensorImage` utils.

(I'm just typing in the text input so it might have errors, but basically correct)

```
TensorImage image = TensorImage.fromBitmap(bitmap)
ByteBuffer buffer = image.getTensorBuffer().getBuffer()
```

The Support library also provide utils for image cropping. Please check out: https://www.tensorflow.org/lite/inference_with_metadata/lite_support

**Comment by yuyecreus** [comment]
> You can try to use our `TensorImage` utils.
> 
> (I'm just typing in the text input so it might have errors, but basically correct)
> 
> ```
> TensorImage image = TensorImage.fromBitmap(bitmap)
> ByteBuffer buffer = image.getTensorBuffer().getBuffer()
> ```
> 
> The Support library also provide utils for image cropping. Please check out: https://www.tensorflow.org/lite/inference_with_metadata/lite_support

Thank you!

When trying:

```
val model = GtsrbMegasmallcnnTf.newInstance(this)
var resized = Bitmap.createScaledBitmap(bitmap, 256, 256, true)
var image = TensorImage.fromBitmap(resized)
var byteBuffer = image.getTensorBuffer().getBuffer()

val inputFeature0 = TensorBuffer.createFixedSize(intArrayOf(1, 256, 256, 3), DataType.FLOAT32)
inputFeature0.loadBuffer(byteBuffer)

val outputs = model.process(inputFeature0)
val outputFeature0 = outputs.outputFeature0AsTensorBuffer
```

I now obtain:

The size of byte buffer and the shape do not match.

**Comment by xunkai55** [comment]
@yuyecreus Hi, sorry for the late reply. I wonder if you already solve the "size and shape do not match" problem.
