### ISSUE TITLE
Integer input and Float output

### ISSUE THREAD

**Issue by yuyecreus** [tensorflow/tflite-support#623]
Hello, 

So I am working in Android Studio with a Transformer model that receives input sequences consisting of **integer** tokens and outputs a **float** array of probabilities:

```
int[][] input = tokenizeInputText(text);
float[][] output = new float[1][labels.size()];
```

Then, when I run:

`tflite.run(input, output);`

I obtain the following error: 

`Cannot convert between a TensorFlowLite tensor with type FLOAT32 and a Java object of type [[I (which is compatible with the TensorFlowLite type INT32).`

I tried to represent the inputs as floats and the error was gone but the model performance I was obtaining was not correct at all. Thank you!

**Comment by lu-wang-g** [comment]
From the error message, it seems that your model expects float input. Do  you mind to share your model for us to investigate?

**Comment by yuyecreus** [comment]
> From the error message, it seems that your model expects float input. Do you mind to share your model for us to investigate?

Here it is. Thank you! https://www.dropbox.com/s/qcznjuhmlhb7abt/transformer.tflite?dl=0

By the way, when I train it in Tensorflow i feed it sequences of INT32 values. Maybe in the converter it specifies floats by default but what I feed it is Integer.

**Comment by lu-wang-g** [comment]
You're right. You need to specify it through conversion. If you open your model using [Netron](https://netron.app/), you'll find both the input/output tensors are float. See the screenshot below.

![image](https://user-images.githubusercontent.com/47436172/127233987-4d897b8b-56b7-424d-b077-c5ab52a5bd18.png)

**Comment by yuyecreus** [comment]
Solved by defining float inputs to the model. Bad results was due to bad real-time preprocessing of the data
