### ISSUE TITLE
Question on what number does tflite model maker dataloader resize images to 

### ISSUE THREAD

**Issue by SarthakJaingit** [tensorflow/tflite-support#624]
Hi, 

I was working with the tflite model maker and I was wondering when creating a data loader like this: 
`
train_dataloader = object_detector.DataLoader.from_pascal_voc('/content/voc_train_images', 
                                                        '/content/voc_train_xml', 
                                                        label_map= {1: "egg", 2: "TSSM", 3: "californicus", 4: "californicus egg"})
`
And creating a model like this: 
`
model = object_detector.create(train_dataloader, model_spec=effecient_detlite0_spec, epochs=3, batch_size=2,
                               train_whole_model=True, validation_data=train_dataloader)
`

What size are images resized to. 

Thanks

**Comment by lu-wang-g** [comment]
@lintian06 could you please take a look at this question?

**Comment by lintian06** [comment]
The image size of the model input is 320x320.

**Comment by lu-wang-g** [comment]
Closing the issue. Feel free to reopen.
