### ISSUE TITLE
Sound classification with custom model

### ISSUE THREAD

**Issue by yuyecreus** [tensorflow/tflite-support#626]
Hello everybody :)

I am using the Sound Classification tensorflow template for building an app in Android Studio. The template uses a yamnet model, but when I import my custom model I obtain the following error.

I would also like to define my own labels and classes because my Sound Classificaiton custom model has been trained in a different dataset than the yamnet model. 

`Error occurred when initializing AudioClassifier: Models are assumed to have the ModelMetadata and SubGraphMetadata.` 

What does it mean? 

Thank you!

**Comment by wangtz** [comment]
Hi Roger,

It means that you didn't populate metadata for this model, which is required for inference using task library. 

You can do so using this library: https://github.com/tensorflow/tflite-support/blob/master/tensorflow_lite_support/metadata/python/metadata_writers/audio_classifier.py

Here is an example how it's being used: https://github.com/tensorflow/examples/blob/5c4d9ef354e4843ce1528070e8de35a50f6e3372/tensorflow_examples/lite/model_maker/core/task/model_spec/audio_spec.py#L115

Let me know if it works for you.

**Comment by lu-wang-g** [comment]
Closing the issue. Feel free to reopen.
