### ISSUE TITLE
ByteBuffer allocation for RGBA Images

### ISSUE THREAD

**Issue by yuyecreus** [tensorflow/tflite-support#629]
Hello everybody :)

I trained a CNN with tensorflow on RGBA images, so when I export it to TFLite and import it to Android Studio I get the suggestion:

`val inputFeature0 = TensorBuffer.createFixedSize(intArrayOf(1, 256, 256, 4), DataType.FLOAT32)`

Now, I want to load images from the media storage and predict a class for them so what I do:

```
var resized = Bitmap.createScaledBitmap(bitmap, 256, 256, true)
var byteBuffer = ByteBuffer.allocate(256 * 256 * **16**)
```

I have set a value of 16 because I've found it is the only one working... However, when I load images from the media storage I get wrong classifications always and most of the time the model just predicts the first class (out of 43).  The complete code I am using is:

```
val model = Cnn.newInstance(this)

var resized = Bitmap.createScaledBitmap(bitmap, 256, 256,true)
var byteBuffer = ByteBuffer.allocate(256 * 256 * 16)

resized.copyPixelsToBuffer(byteBuffer)

//var image = TensorImage.fromBitmap(resized)
//var byteBuffer = image.getTensorBuffer().getBuffer()

val inputFeature0 = TensorBuffer.createFixedSize(intArrayOf(1, 256, 256, 4), DataType.FLOAT32)
inputFeature0.loadBuffer(byteBuffer)

val outputs = model.process(inputFeature0)
val outputFeature0 = outputs.outputFeature0AsTensorBuffer
```

Am I doing anything wrong? 

Thank you guys!

**Comment by xunkai55** [comment]
Hi, continued the suggestion in the other issue, I still suggest you to make sure that your model is expecting 256 * 256 * 4 (width * height * channel) floats as input.

Secondly, most image classification model expects float value in range (0, 1) or (-1, 1), or a small interval like (-2.5, 2.5). This process is called "normalization". `copyPixelsToBuffer` still generates integers in (0, 255)

Anyway, you need to double check that the data provided in training and inference obey the same distribution.

**Comment by xunkai55** [comment]
I'm just a bit curious on why it need **16** in the byte buffer allocation. That indicates you have 4 channels and each channel is a 32-bit value (likely a `float32`). That's not common. Mostly I see people have 4 channels with `RGBA_8888` configuration, and each channel is a `uint8` value.

Could you try

1. Use `ByteBuffer.allocate(256 * 256 * 4)`
2. Use `TensorBuffer.createFixedSize(intArrayOf(1, 256, 256, 4), DataType.UINT8)`

If you do expect float input for your model, that might be the normalization case I mentioned. You may uncomment the `TensorImage` thing, and use the following normalization code:

```
ImageProcessor preprocessor = new ImageProcessor.Builder()
        .add(new NormalizeOp(/*mean*/, /*std*/)
        .build();
TensorImage normalized = preprocessor.process(image);
```

**Comment by yuyecreus** [comment]
> Could you try
> 1. Use ByteBuffer.allocate(256 * 256 * 4)
> 2. Use TensorBuffer.createFixedSize(intArrayOf(1, 256, 256, 4), DataType.UINT8)


This gives:

`Cannot convert between a TensorFlowLite buffer with 1048576 (256*256*16) bytes and a Java Buffer with 262144 (256*256*4) bytes.`

So yes, my model expects RGBA float32 data. 

> If you do expect float input for your model, that might be the normalization case I mentioned. You may uncomment the TensorImage thing, and use the following normalization code:

What I try:

```
val model = Cnn.newInstance(this)

var resized = Bitmap.createScaledBitmap(bitmap, 256, 256,true)

var image = TensorImage.fromBitmap(resized)
var preprocessor = ImageProcessor.Builder().add(NormalizeOp(0.5f, 0.5f)).build();
var normalized = preprocessor.process(image);
var byteBuffer = normalized.getTensorBuffer().getBuffer()


val inputFeature0 = TensorBuffer.createFixedSize(intArrayOf(1, 256, 256, 4), DataType.FLOAT32)
inputFeature0.loadBuffer(byteBuffer)

val outputs = model.process(inputFeature0)
val outputFeature0 = outputs.outputFeature0AsTensorBuffer
```

And I get:

`The size of byte buffer and the shape do not match`

And when I debug the size of the buffer of the preprocessed image (normalized) I obtain:

`java.nio.DirectByteBuffer[pos=0 lim=786432 cap=786432]. `

Which makes no sense to me! (786432 = 256 * 256 * 12) 

Anyway, it feels we're getting close. Thank you!

**Comment by xunkai55** [comment]
Well yes, currently our util `TensorImage` only supports RGB data (3 channels, 4 bytes each so its 12 in your findings). In other words, it always drops A channel directly.

I guess in this case, you probably want to write your own normalization code, and convert `Bitmap` to `ByteBuffer`. What just came into my mind:

1. Use `getColors` to extract pixel values from `resized` Bitmap
2. Iterate the pixels, normalize it from ARGB int32 (not RGBA!) into 4 float32. Commonly you want `(p - 127) / 255.0` or something like this.
3. Use a `FloatBuffer` or `ByteBuffer` to wrap the float32. Be sure to make the `order()` correct, because Java sometimes use big endian encoding.

**Comment by yuyecreus** [comment]
Makes sense. Thank you @xunkai55. I am going to close this because I have retrained my model on RGB data (and not RGBA). Still it is float32 so TensorImage utils + Preprocessor now works. Thank you very much! :)
