### ISSUE TITLE
Adding dependencies for MlImageAdapter in Android app

### ISSUE THREAD

**Issue by sohail-jogo** [tensorflow/tflite-support#639]
I am not able to use MlImageAdapter to convert an ML Image  to TensorImage. 
error: Cannot resolve symbol 'MlImageAdapter' .

The dependencies are in the BUILD file. I am not sure how I can add this library in gradle file (android Java).

**Comment by lu-wang-g** [comment]
@xunkai55 can you please take a look?

**Comment by xunkai55** [comment]
@sohail-jogo Hi, may I know which version of TFLite support artifacts are you using? Currently the `MlImageAdapter` only appears in our nightly snapshot builds.

**Comment by sohail-jogo** [comment]
Currently, I am using the following: 

```
implementation 'org.tensorflow:tensorflow-lite:2.5.0'
implementation 'org.tensorflow:tensorflow-lite-gpu:0.0.0-nightly'
implementation 'org.tensorflow:tensorflow-lite-support:0.2.0'
```

**Comment by sohail-jogo** [comment]
Simply adding the following dependency doesn't work : 

`implementation "org.tensorflow:tensorflow-lite-task-vision:0.0.0-nightly-SNAPSHOT"`

Is there additional step that I am missing here?

**Comment by sohail-jogo** [comment]
Is there any plan to add this MLImageAdapter into the stable version any time soon? I think it might be a good idea if i wait and then use this, as my app is in production.

**Comment by xunkai55** [comment]
> Simply adding the following dependency doesn't work :
> 
> `implementation "org.tensorflow:tensorflow-lite-task-vision:0.0.0-nightly-SNAPSHOT"`
> 
> Is there additional step that I am missing here?

It's likely that the dependency is not refreshed. Could you please try clean the project, and use `./gradlew --refresh-dependencies` or equivalent commands to refresh the dependency?

And if that doesn't work, probably it's caching the `0.2.0` which shadows `0.0.0-nightly`. You can try `0.0.0-nightly-SNAPSHOT!!` to make it strict.

> Is there any plan to add this MLImageAdapter into the stable version any time soon? I think it might be a good idea if i wait and then use this, as my app is in production.

Yes, we plan to include this feature in the next minor version `0.3.0`. It's going to happen in this quarter.

**Comment by sohail-jogo** [comment]
Alright then, thats good know. I guess I will wait till then as I still can't use it. 
I really appreciate a quick response from you. 
Thanks a lot!

**Comment by sohail-jogo** [comment]
It worked now btw! I had to comment out my other tensorflow dependencies. 
https://drive.google.com/file/d/1gfBjfEw8EMkWzALad9dAoBjiHTxkKghm/view?usp=sharing

**Comment by xunkai55** [comment]
Good to know!
