### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement tflite-runtime==2.1.0.post1

### ISSUE THREAD

**Issue by waqasakram117** [tensorflow/tflite-support#700]
I have a tflite model that I want to run locally
pip 
 tflite-runtime==2.1.0.post1

Generates ERROR: Could not find a version that satisfies the requirement tflite-runtime==2.1.0.post1 
My system is Mac Big Sur 11.6
Someone, please help me.

**Comment by lu-wang-g** [comment]
2.1.0 does not support BigSur, only for Catalina. You can install the latest version, 2.5.0, by:
```
python3 -m pip install --extra-index-url https://google-coral.github.io/py-repo/ tflite-runtime
```

See more instructions [here](https://www.tensorflow.org/lite/guide/python#install_tensorflow_lite_for_python).

**Comment by kahbenya** [comment]
> 2.1.0 does not support BigSur, only for Catalina. You can install the latest version, 2.5.0, by:
> 
> ```
> python3 -m pip install --extra-index-url https://google-coral.github.io/py-repo/ tflite-runtime
> ```
> 
> See more instructions [here](https://www.tensorflow.org/lite/guide/python#install_tensorflow_lite_for_python).

```
python3 -m pip install --extra-index-url https://google-coral.github.io/py-repo/ tflite-runtime==2.5.0.post1
```
resolved my dependency issue for the specific version of `tflite-runtime`
