### ISSUE TITLE
How to allocate memory for output tensor for model which takes in dynamic input dimensions ?

### ISSUE THREAD

**Issue by Gojo1729** [tensorflow/tflite-support#701]
Hi,
I've a tflite model which takes which is working on all the image formats except for jpg images in an Android app, this works fine in python. Below is the code for preprocessing the image. I'm reading the image as bitmap. My model outputs the tensor of the same dimension as the input tensor.  
```

   Interpreter.resizeInput(
            inputIndex, intArrayOf(1, inputBitMap.height, inputBitMap.width, 3)
        )
        Interpreter.allocateTensors()


        val inputTensorImage = TensorImage(DataType.FLOAT32)

        val size = inputBitMap.byteCount

        inputTensorImage.load(inputBitMap)

        val limit = inputTensorImage.buffer.limit()

        val outputTensorBuffer = TensorBuffer.createFixedSize(
            intArrayOf(1, inputBitMap.height, inputBitMap.width, 3),
            DataType.FLOAT32
        ).buffer

      Interpreter.run(inputTensorImage.tensorBuffer.buffer, outputTensorBuffer)

```

I'm getting the following error for only jpg images - 
`java.lang.IllegalArgumentException: Cannot copy from a TensorFlowLite tensor (StatefulPartitionedCall:0) with 2899200 bytes to a Java Buffer with 2889600 bytes.`

I checked the inputtensor and outputtensor size both seems to be correct.

Need help in debugging this issue.

**Comment by Gojo1729** [comment]
Actually now I found out the issue is not with the image type but with image dimensions, if the aspect ratio (width/height) is not 1 then I'm getting this error.

**Comment by Gojo1729** [comment]
The issue is with the dynamic input shape, how should I allocate size to output tensor where the model input is of dynamic size ?

**Comment by lu-wang-g** [comment]
Please see the Javadoc [here](https://github.com/tensorflow/tensorflow/blob/60dacf192da652f9a6bed796c73abfa6d8fd2fff/tensorflow/lite/java/src/main/java/org/tensorflow/lite/Tensor.java#L131-L152) for instructions of invoking dynamic shape model.

**Comment by Gojo1729** [comment]
I'm using tflite 2.5.0 and the above method mentioned is not available

**Comment by Gojo1729** [comment]
2.6.0 , got it 👍

**Comment by Gojo1729** [comment]
Is there a way to handle this in tflite version before 2.5.0 ?

**Comment by lu-wang-g** [comment]
If you know the output shape w.r.t each input, you can resize the output tensor (outputTensorBuffer) properly. Then 
```
Interpreter.run(inputTensorImage.tensorBuffer.buffer, outputTensorBuffer)
```
should be able to work.
