### ISSUE TITLE
Select Ops support in org.tensorflow.lite.task.vision.detector

### ISSUE THREAD

**Issue by Parvel** [tensorflow/tflite-support#705]
Hi,

I'm trying to get a converted .tflite model which contains select OPs (CombinedNonMaxSuppression) working on an Android app which used tflite task library to consume the model with ObjectDetector.

TFLite version: 2.7RC1/2.6/2.5
TF Task Lib version:  tensorflow-lite-task-vision:0.2.0
OS: Android 8.0/9.0 API Level 27-29

I have followed the [link](https://www.tensorflow.org/lite/guide/ops_select) to build customized tflite and select op AARs. And the model can be loaded from plain Interpreter Java APIs, with selected OP linked at loading time as  in the Android app snippets:

```

    private static final String TFOD_MODEL_ASSET = "select_ops_model.tflite";
    private static final String[] LABELS = {
            "label 1",
            "label 2"
    };

    Interpreter interpreter;

    private void loadModelFromAsset(String assetName, String... labels) {
        try {
            AssetManager assetManager = AppUtil.getDefContext().getAssets();
            AssetFileDescriptor afd = assetManager.openFd(assetName);
            try (FileInputStream fis = afd.createInputStream()) {
                MappedByteBuffer modelData = fis.getChannel()
                        .map(FileChannel.MapMode.READ_ONLY, afd.getStartOffset(), afd.getDeclaredLength());
                interpreter = new Interpreter(modelData);
            }
        } catch (IOException e) {
            throw new RuntimeException("TFObjectDetector loadModelFromAsset failed", e);
        }
    }

    loadModelFromAsset(TFOD_MODEL_ASSET, LABELS);

```

As logcat showed the TFLite model has triggered the Flex OP dynamic loading logic handled by [NativeInterpreterWrapper.java](https://github.com/tensorflow/tensorflow/blob/085b0ae1d5785f9b6ca86e9e59be58b248defa77/tensorflow/lite/java/src/main/java/org/tensorflow/lite/NativeInterpreterWrapper.java#L615)

```

1969-12-31 18:04:21.589 1544-1646/xxx I/Core: Attempting to switch to App TFLite Model Load Test
1969-12-31 18:04:21.692 1544-1660/xxx I/tflite: Initialized TensorFlow Lite runtime.
1969-12-31 18:04:21.718 1544-1660/xxx I/tflite: Created TensorFlow Lite delegate for select TF ops.
1969-12-31 18:04:21.721 1544-1660/xxx I/tflite: TfLiteFlexDelegate delegate: 1 nodes delegated out of 313 nodes with 1 partitions.
1969-12-31 18:04:21.722 1544-1660/xxx I/tflite: Replacing 1 node(s) with delegate (TfLiteFlexDelegate) node, yielding 2 partitions.
```

However, such initialization when digesting the model data with ObjectDetector in task vision library, is handled by JNI and mostly the native C++ codes, where no similar model flex OP probe is implemented  in [tflite_engine.cc](https://github.com/tensorflow/tflite-support/blob/8c0a369197e09be72b4833235a2b04d21de3e09d/tensorflow_lite_support/cc/task/core/tflite_engine.cc) yet, upon initializing the Interpreter.

If loading the model via the ObjectDetector API: createFromBuffer or createFromFile, the model loading would fail with following complaining:

```
1969-12-31 18:06:53.288 1560-1684/xxx I/tflite: Initialized TensorFlow Lite runtime.
1969-12-31 18:06:53.304 1560-1684/xxx E/tflite: Regular TensorFlow ops are not supported by this interpreter. Make sure you apply/link the Flex delegate before inference.
1969-12-31 18:06:53.304 1560-1684/xxx E/tflite: Node number 312 (FlexCombinedNonMaxSuppression) failed to prepare.


```

My questions: 

1. Would there be an existing way of building this select op support in vision task lib ObjectDetector by enabling some bazel compile options? The [link](https://www.tensorflow.org/lite/guide/ops_select) mentioned for C++ projects, one bazel dependency could be added but that's for TFLite project. Not sure if there's a clear bazel procedure to rebuild the tflite-support components.
2. Or could similar logic of flex op support be ported to Object Detector, or even the common task-base lib?
3. Any other workaround like configure the delegates of flex ops before ObjectDetector initialize the Interpreter in JNI?

Thank you!

**Comment by lu-wang-g** [comment]
Custom ops is not supported currently in ObjectDetector. I've created an internal feature request to track it.  I'll see if I can have sometime to add the feature this week.

**Comment by Parvel** [comment]
Thank you Lu :) that would be perfect.

**Comment by Parvel** [comment]
Thank you @lu-wang-g for clarification :) This is still a great opportunity for our FTC team to learn such in-depth knowledge of using TFLite for robotics.

**Comment by lu-wang-g** [comment]
No problem! I'm closing this issue for now. Feel free to reopen if you have any questions or issues using the approach I mentioned previously.
