### ISSUE TITLE
How to compile from source to whl, and then use pip to install it

### ISSUE THREAD

**Issue by lasyka** [tensorflow/tflite-support#711]
Hi there, this is not bug,  but i dont know where to ask question.  
How to compile  tflite-support from source ,and package it to whl, then use pip to install it?

**Comment by lu-wang-g** [comment]
It can be done with something like:
```
bazel build -c opt --action_env PYENV_VERSION="${py_version}" \
      --crosstool_top="@ubuntu16.04-py3-gcc7_manylinux2010-cuda10.0-cudnn7-tensorrt5.1_config_cuda//crosstool:toolchain" \
      tensorflow_lite_support/tools/pip_package:build_pip_package

./bazel-bin/tensorflow_lite_support/tools/pip_package/build_pip_package --dst wheels --version "${VERSION}"
```
But  you need to first configure the python environment and cross toolchain properly.

**Comment by lasyka** [comment]
> It can be done with something like:
> 
> ```
> bazel build -c opt --action_env PYENV_VERSION="${py_version}" \
>       --crosstool_top="@ubuntu16.04-py3-gcc7_manylinux2010-cuda10.0-cudnn7-tensorrt5.1_config_cuda//crosstool:toolchain" \
>       tensorflow_lite_support/tools/pip_package:build_pip_package
> 
> ./bazel-bin/tensorflow_lite_support/tools/pip_package/build_pip_package --dst wheels --version "${VERSION}"
> ```
> 
> But you need to first configure the python environment and cross toolchain properly.
Thank you.
