### ISSUE TITLE
Didn't find op for builtin opcode 'MIRROR_PAD' version '2'

### ISSUE THREAD

**Issue by AlexisPapaioannou** [tensorflow/tflite-support#722]
I run a tflite model on a cortex m4 and I received the following error. Is there any way to import any built_in function?

"Didn't find op for builtin opcode 'MIRROR_PAD' version '2'. An older version of this builtin might be supported. Are you using an old TFLite binary with a newer model?

Failed to get registration from op code MIRROR_PAD
 
AllocateTensors() failed"

**Comment by lu-wang-g** [comment]
Can you try using the latest TFLite runtime version v2.7?
