### ISSUE TITLE
tf.lite.Interpreter returns same predictions for different input

### ISSUE THREAD

**Issue by tempdeltavalue** [tensorflow/tflite-support#727]
Hi, first of all sorry for poor information which I provide in this issue

But I got same predictions for different input using tf.lite.Interpreter, can somebody explain where is the problem and how to fix it? 

Also I attached image (in blue - part of input, in red - mean of output (if you print whole output it also same for different inputs))

![Screenshot 2021-12-10 185510](https://user-images.githubusercontent.com/36921178/145602867-650036ac-b12e-482c-8d02-062f023422f9.png)

some code:

```
tflite_interpreter = tf.lite.Interpreter(model_path=TFLITE_MODEL)
tflite_interpreter.allocate_tensors()

input_details = tflite_interpreter.get_input_details()
output_details = tflite_interpreter.get_output_details()

input =  np.random.uniform(low=-1, high=1, size=(1, 224, 224, 3))
input = input.astype(np.float32)
print(input[0, 0:2])
tflite_interpreter.set_tensor(input_details[0]['index'], input)

tflite_interpreter.invoke()

tflite_model_predictions = tflite_interpreter.get_tensor(output_details[0]['index'])
print("mean", np.mean(tflite_model_predictions))
print("std", np.std(tflite_model_predictions))
print("Predictions", tflite_model_predictions[0, 0:2])
tflite_interpreter.reset_all_variables()
```

Will be thankful for any help :)

**Comment by lu-wang-g** [comment]
Can you try printing the values in `tflite_mode_predictions` instead of the mean? It is possible that the output values add up to a constant value. For example, the sum of output scores of an image classification model always add up to 1.

**Comment by tempdeltavalue** [comment]
@lu-wang-g Yeap, here's screenshot of predictions

<img width="1316" alt="Screenshot 2021-12-10 at 22 02 23" src="https://user-images.githubusercontent.com/36921178/145634791-58b7041c-89d7-423f-bbfa-66f1756c6528.png">

by the way tflite code from my question in general is copy-paste from here...
https://colab.research.google.com/github/frogermcs/TFLite-Tester/blob/master/notebooks/Testing_TFLite_model.ipynb

**Comment by lu-wang-g** [comment]
Do you mind to share your model with me so that I can take a look?

**Comment by tempdeltavalue** [comment]
of course (but there's nothing super interesting just model from keras.applications)

you can edit this colab (also probably you need to setup your TFLITE_MODEL)

https://colab.research.google.com/drive/1GUr6RhMMyAnxyxZEOIK42QnEQYIMo6Cf?usp=sharing

**Comment by lu-wang-g** [comment]
The inference script is OK. I double checked it with other models, and it works fine.

But I think the problem is the converted model. If you open it up in Netron, you'll find a standalone op, "x0", with your input and output tensor. To convert a Keras model, [here](https://www.tensorflow.org/lite/convert#convert_a_keras_model_) is the recommended approach.

**Comment by tempdeltavalue** [comment]
@lu-wang-g Thank you very much for this... (next time try to open models by Netron myself :) )
