### ISSUE TITLE
Adding Metadat to the model.

### ISSUE THREAD

**Issue by tirumala007** [tensorflow/tflite-support#728]
i have downloaded the trained model from https://teachablemachine.withgoogle.com/  which is a floating point model. i can't download the quantized model. when i add the downloaded file(2 MB file) to the project,  the apk size has increased(nearly 30 MB). but i gave me an error about normalization. it requires meta data. i don't know how to add metadata to tflite. help me with adding meta data. is there any way to decrease the apk size?
i'm trying for image classification.

**Comment by lu-wang-g** [comment]
See this [tutorial](https://www.tensorflow.org/lite/convert/metadata_writer_tutorial#image_classifiers) about adding metadata for Image Classification models. You'll need to provide normalization params and labels file that are essential in pre and post processing.

Can you please show my your inference code and dependencies?
