### ISSUE TITLE
Is There Any Prebuilt Library Repository?

### ISSUE THREAD

**Issue by fatihkiralioglu** [tensorflow/tflite-support#732]
Hi,
I want to try Tensorflow lite firtly in Windows and then Android. I need prebuilt libraries. 
Is there any place to download these libraries?
Thanks

**Comment by lu-wang-g** [comment]
I don't think we distribute prebuilt libraries. But you can build one from the source code. See https://github.com/tensorflow/tensorflow/issues/38852#issuecomment-618852882.

**Comment by fatihkiralioglu** [comment]
thanks, I have built it via Cmake

**Comment by SHagerGEL** [comment]
Can you share youre CMakeLists.txt?

**Comment by Frontkick** [comment]
> I don't think we distribute prebuilt libraries. But you can build one from the source code. See [tensorflow/tensorflow#38852 (comment)](https://github.com/tensorflow/tensorflow/issues/38852#issuecomment-618852882).

can you please provide link for tensorflow lite build libraries

**Comment by ValYouW** [comment]
@Frontkick From time to time I publish pre-built libs of the C-API for android and windows. [tflite-dist](https://github.com/ValYouW/tflite-dist)
