### ISSUE TITLE
Is it possible to train a model using the C++

### ISSUE THREAD

**Issue by pedropgusmao** [tensorflow/tflite-support#733]
Hi, is it possible to use C++ TFLite to train a model? I could only find code for Python https://www.tensorflow.org/lite/examples/on_device_training/overview
Thanks in advance

**Comment by lu-wang-g** [comment]
@haozha111 Is it recommended to use the C++ API?

**Comment by haozha111** [comment]
Yes, technically you can use C++ API to train a model with TF Lite. I think the main API to achieve this purpose is through the multi-signature API (https://www.tensorflow.org/lite/guide/signatures), and you can run `train` signatures by using the signature runner class. Please feel free to give it a try, thanks!
