### ISSUE TITLE
Documentation for LabelFileMd file format

### ISSUE THREAD

**Issue by Wirg** [tensorflow/tflite-support#746]
Hi,

I am looking for information about `LabelFileMd` file and I was not able to find it clearly.
Does the label file have to be a .txt with one "label" by line?
If I have a jsonl-like structure with multiple and possibly nested entries, can I make it work or does it have to be broken into one file by key?

Example :
```jsonl
{
 "key_1": "value1_1",
 "key_2": "value2_1"
}
{
 "key_1": "value1_2",
 "key_2": "value2_2"
}
{
 "key_1": "value1_3",
 "key_2": "value2_3"
}
```

**Comment by lu-wang-g** [comment]
If you want to use Task Library or Support Library to automatically load and parse the label file, the file needs to be a txt file, such as this [one](https://github.com/tensorflow/tflite-support/blob/master/tensorflow_lite_support/metadata/python/tests/testdata/image_classifier/labels.txt). If you don't expect to leverage Task Library and Support library, you can use any formats, but you'll need to create a parser by yourself.
