### ISSUE TITLE
Add `create_from_file` method to remaining Python Task APIs

### ISSUE THREAD

**Issue by khanhlvg** [tensorflow/tflite-support#760]
We want to add a convenient way to create a task object with a model file and the default option.

Here is the commit that add it to the ImageClassifier. 
https://github.com/tensorflow/tflite-support/commit/92e086446e9fe6ed7bc4b3e5060ade9a6aa3085f

@kinaryml Could you help us create the API for the other tasks that has been implemented. Please also move the TODO out of pydoc as in the commit. Thanks.

**Comment by kinaryml** [comment]
@khanhlvg Alrighty, will do.

**Comment by kinaryml** [comment]
@khanhlvg I've raised a PR [here](https://github.com/tensorflow/tflite-support/pull/761).
