### ISSUE TITLE
Write unit tests for Python AudioRecord

### ISSUE THREAD

**Issue by khanhlvg** [tensorflow/tflite-support#764]
@kinaryml 
I expect that you'll have to do these things:

* Mock sounddevice.InputStream because the CI servers that run the tests don't have a soundcard so sounddevice will fail.
  * Use the [unittest.mock](https://docs.python.org/3/library/unittest.mock.html) to mock the class. It's a requirement for Python mock at Google.
  * I think you need to use `@patch('sounddevice.InputStream')` to patch the class, and use the callback to add dummy data to the buffer of TensorAudio.
* Then in the unittest, check if the dummy data you passed to the callback matches with what the TensorAudio#read function returns.

**Comment by kinaryml** [comment]
@khanhlvg I've added a test to a branch in the other repo. Could you check it out and let me know your thoughts? Here's the link to the commit: https://github.com/khanhlvg/tflite-support/commit/58601b1d16675184912560b800b3e3b1eb074d7f

**Comment by kinaryml** [comment]
@khanhlvg The CI server should be able to run the following test: 
https://github.com/khanhlvg/tflite-support/blob/tensor-audio-impl-and-tests/tensorflow_lite_support/python/task/audio/core/audio_record_test.py

**Comment by khanhlvg** [comment]
Thanks Kinar. For code readability, I expected mocking InputStream entirely rather than patch some features of the original class, which makes a lot of assumption about the inner working of InputStream.

I updated the test code to something that looks like this, and I've sent the code for internal review.
https://github.com/khanhlvg/tflite_raspberry_pi/blob/main/audio_classification/audio_record_test.py

I'll summarize the changes once the review has completed and will let know when to send the next PR for TensorAudio.

**Comment by kinaryml** [comment]
@khanhlvg Agreed. For code readability, it makes sense to mock the whole class. I've aligned the tests with those new changes for now.

**Comment by khanhlvg** [comment]
Implemented in https://github.com/tensorflow/tflite-support/commit/5490f096933fe0348d45c8ca8c955e1f158f8971
