### ISSUE TITLE
Correct the return type in pybinds

### ISSUE THREAD

**Issue by khanhlvg** [tensorflow/tflite-support#776]
Some pybinds returns a proto of the `vision` namespace while the Python layer expects a proto of the `processor` namespace. [(example)](https://github.com/tensorflow/tflite-support/blob/980ebd734eb015fb84d91c1bde8f67179fd458e5/tensorflow_lite_support/python/task/vision/pybinds/_pywrap_image_embedder.cc#L91).

The test still pass because Python doesn't do strict type check. As long as the protos are identical, there's no issue raised. However, this may cause issue in the future so we want to change the output type of pybinds to use protos in the `processor` and cast [(example)](https://github.com/tensorflow/tflite-support/blob/980ebd734eb015fb84d91c1bde8f67179fd458e5/tensorflow_lite_support/python/task/vision/pybinds/_pywrap_image_embedder.cc#L97) the `vision` proto to the corresponding `processor` proto before returning.

@kinaryml Could you do an audit of all existing tasks and send a PR to correct the return type?

**Comment by kinaryml** [comment]
@khanhlvg The text and audio embedder seem to expect protos in the `processor` namespace by default so I've raised a [PR](https://github.com/tensorflow/tflite-support/pull/778) for the remaining tasks that require explicit checks and conversions.

**Comment by khanhlvg** [comment]
Fixed in https://github.com/tensorflow/tflite-support/commit/a1fa6a2bc04dcdbfcd10acaba8dfdf8e58880684
