### ISSUE TITLE
Remove Associated file

### ISSUE THREAD

**Issue by anhhoang26** [tensorflow/tflite-support#777]
Rencently, I trained a model image classify on Vertex AI. 
Model packed assoiciated file in this. 
I want remove it.

**Comment by lu-wang-g** [comment]
You can simply unpack the tflite model using zip, such as `unzip xxx.tflite`. It will give you the tflite model without associated files and the standalone associated files.

**Comment by anhhoang26** [comment]
@lu-wang-g  it doesn't work. I unpacked file model(xxx.tflite), i received 2 file : xxx.tflite and labels.txt. But when i unpack it again, i still get both xxx.tflite and labels.txt
![Screenshot from 2022-04-07 13-41-25](https://user-images.githubusercontent.com/57597581/162136373-c2b7f2b1-26bf-406b-a1ea-78e9f1ee6cf2.png)
>

**Comment by kinaryml** [comment]
I think these two links might be helpful.
Vertex AI: https://cloud.google.com/vertex-ai/docs/export/export-edge-model#output-files
AutoML Vision (does produce a `dict.txt` label file): https://cloud.google.com/vision/automl/docs/export-edge#tf-lite

The Vertex AI model shouldn’t produce a label file AFAIK.

**Comment by lu-wang-g** [comment]
@anhhoang26 how about `zip -d model.tflite labels.txt`?

**Comment by anhhoang26** [comment]
@lu-wang-g Thanks verymuch. It works !
