### ISSUE TITLE
Update pybinds so that Python APIs throw error instead of returning statusOr

### ISSUE THREAD

**Issue by khanhlvg** [tensorflow/tflite-support#779]
Yuqi has pushed a commit to change how Python layer returns errors: throwing an Error when there's an error occur, rather than returning the error status.
https://github.com/tensorflow/tflite-support/commit/d8ddc0d16b32bb636fd9ac3075e4b380afff86ba

@kinaryml Could you do these things?
* Apply this change to your WIP image_segmenter implementation.
* Send a separated PR to update the remaining tasks to follow this pattern.

**Comment by kinaryml** [comment]
@khanhlvg Alright, will do.

**Comment by kinaryml** [comment]
@khanhlvg I've updated the ImageSegmenter WIP implementation and also raised a [PR](https://github.com/tensorflow/tflite-support/pull/780) to incorporate the new error handling changes.

**Comment by khanhlvg** [comment]
Fixed in https://github.com/tensorflow/tflite-support/commit/1ab917f6716dd680ac51878446a7f4b033701759
