### ISSUE TITLE
Migrate the tests in TFLite Task Library to use TF test

### ISSUE THREAD

**Issue by khanhlvg** [tensorflow/tflite-support#786]
@kinaryml Could you update the tests to use tf.test as in the [image_embedder](https://github.com/tensorflow/tflite-support/blob/9f64b9ed362865a9865643cbbb8fb9b63fc3f0aa/tensorflow_lite_support/python/test/task/vision/image_embedder_test.py#L39) test?

**Comment by kinaryml** [comment]
@khanhlvg Sure thing. Let me create a branch for it and I'll let you know once I've raised the PR.

**Comment by khanhlvg** [comment]
Could you add it to this [PR](https://github.com/tensorflow/tflite-support/pull/784)? It should be a minor change so I'd like to group these minor changes into one PR to reduce the overhead required by the review process.

**Comment by kinaryml** [comment]
@khanhlvg Alright, I'll update the PR title and push the changes.

**Comment by kinaryml** [comment]
@khanhlvg Is it possible to import the `mock` module using `tf.test`? At the moment, I'm not able to access mock using `tf.test.mock`. Could you share your thoughts on this?

**Comment by kinaryml** [comment]
I just investigated a little more and I believe I can use this:

```python
from tensorflow.python.platform import test
_mock = test.mock
```

@khanhlvg Let me know if that sounds good for you?

**Comment by khanhlvg** [comment]
Yes if the test runs then it's good.

**Comment by khanhlvg** [comment]
```
from tensorflow.python.platform import test
_mock = test.mock
```

It turned out that this is an TF internal API and we can't use it in the internal build system. I reverted back the change.

Issue was fixed with https://github.com/tensorflow/tflite-support/pull/784 and https://github.com/tensorflow/tflite-support/commit/d211e4030fcfc85c44256cc2deea7f1d4ecc85dc
