### ISSUE TITLE
Add more tasks to the TFLite Support pip package

### ISSUE THREAD

**Issue by khanhlvg** [tensorflow/tflite-support#790]
This [commit](https://github.com/tensorflow/tflite-support/commit/b1f13f0cb035140de9eebecfb46e7b39e3b1c9c8) added some tasks but we have more tasks implemented.

@kinaryml Could you take a look at the commit and add the missing tasks (e.g audio tasks, text embedder etc.), and test if they work. You can test following the instructions in the commit message.

**Comment by kinaryml** [comment]
@khanhlvg I'll work on this and share a Colab with you to test the new tasks.

**Comment by kinaryml** [comment]
@khanhlvg Here's a [Colab](https://colab.research.google.com/drive/1wzgH8oICEajZNli_8IP7t7wWm1Crl7GJ?usp=sharing
) which tests all the tasks after building and installing the pip wheel. It seems to be running into a segmentation fault error while trying to create the task object using the `create_from_options` method for a task. Could you share your thoughts on this? Let me know if there's a specific GCC version I need to use to build the package.

**Comment by kinaryml** [comment]
A link to the branch with the changes can be found [here](https://github.com/khanhlvg/tflite-support/tree/add-more-tasks-to-pip-package).

**Comment by khanhlvg** [comment]
@kinaryml I got this feedback from Lu. Could you try again?

That's most likely he doesn't install protobuf. If you download the wheel from Pypi, it will also install  the required packages for you, such as [this](https://github.com/tensorflow/tflite-support/blob/7188e5bf3b8679d3eb1ffeaaea852a519260cfb3/tensorflow_lite_support/tools/pip_package/setup.py#L57)
When building it locally, we need to manually install the packages.

**Comment by kinaryml** [comment]
@khanhlvg @lu-wang-g Thanks for pointing out it the issue had to do with the dependencies. I'm able to create and run the tasks now. Although, I had to change the requirements to use `protobuf==3.18.0` instead of `protobuf>=3.18.0`. Runs fine now though.

Here's the updated Colab:
https://colab.research.google.com/drive/1nL8sDEAQuEHcV5z9pJ9DnS_QwtZzM5J9?usp=sharing

**Comment by khanhlvg** [comment]
Thanks Kinar. It looks great!

Can you send a pull request to add the tasks to the Pip package?

**Comment by kinaryml** [comment]
@khanhlvg I've raised a[PR](https://github.com/tensorflow/tflite-support/pull/792) for the remaining tasks.
