### ISSUE TITLE
Under the premise of pursuing the smallest possible tflite-related binary files, which one is more suitable, tflite or tensorflow-lite-task-text?

### ISSUE THREAD

**Issue by catqaq** [tensorflow/tflite-support#810]
Hi, I followed your tutorial to [reduce tflite aar size](https://tensorflow.google.cn/lite/guide/reduce_binary_size?hl=en) baed on my nlp models. But it failed due to the network error related to bazel(https://github.com/tensorflow/tensorflow/issues/55945). Today I found your great tflite-support repo, At first I thought tensorflow-lite-task-text would be smaller than tflite itself, but in fact the former is much larger than the latter in aar format. 
Any idea to reduce tflite related(tflite or tflite-text) binary size?

**Comment by lu-wang-g** [comment]
tensorflow-lite-task-text is the target for [Task Library NL APIs](https://www.tensorflow.org/lite/inference_with_metadata/task_library/overview), which is built on top of TFLite Interpreter. Therefore the binary size will be larger. 

To reduce the binary size, you'll need to customize your own tflite aar as introduced in https://tensorflow.google.cn/lite/guide/reduce_binary_size?hl=en, and build it from source. Therefore, resolving https://github.com/tensorflow/tensorflow/issues/55945 is a pre-requirement. 

If you are interested in using tensorflow-lite-task-text, I can help to provide more instructions further.

**Comment by catqaq** [comment]
Thanks! I have solved this problem.
