### ISSUE TITLE
Serving tflite model on Tensorflow serving API

### ISSUE THREAD

**Issue by surpreetmann** [tensorflow/tflite-support#813]
Is there a way we can serve tflite models on tensorflow serving API? I have converted my tf model to tflite in order to quantize the model for increasing the speed. Now I want to serve this model on TF serving.

**Comment by lu-wang-g** [comment]
What is the status of TFLite with TF Serving, @karimnosseir?

**Comment by karimnosseir** [comment]
@surpreetmann 
Serving has some tflite session to run tflite https://github.com/tensorflow/serving/blob/master/tensorflow_serving/servables/tensorflow/tflite_session.h

You can ask on tensorflow_serving about the code status as we don't maintain this part.

Thanks
