### ISSUE TITLE
Migrate Python APIs to use dataclasses instead of protobuf in public API

### ISSUE THREAD

**Issue by khanhlvg** [tensorflow/tflite-support#817]
Using protobuf directly in Python APIs have created some usability issues:
* No auto-completion suggestion
* No API docstring

We want to migrate the user facing API from exposing protobuf directly to use dataclasses. This [commit](https://github.com/tensorflow/tflite-support/commit/394a4c7a11330704c7dee9fe398d5d53320ea698) prototypes the change for one class. @kinaryml Could you help to update the code for other classes?

We'll tackle the changes per task to minimize the amount of code changes per PR. Let's do it in this order:
* PR1: ObjectDetector
* PR2: ImageSegmenter
* PR3: ImageClassifier and AudioClassifier
* PR4: ImageEmbedder, TextEmbedder and AudioEmbedder

**Comment by kinaryml** [comment]
@khanhlvg What do we do about `DetectionResult` for the ObjectDetector though? Should I convert that to a dataclass too or do you have another PR for it? It seems that the way we evaluate the results will change drastically if we happen to make all of the protos to use dataclasses. Let me know what you think.

**Comment by kinaryml** [comment]
@khanhlvg Here's the link to the branch with the changes for the `ObjectDetector` API and tests. PTAL.

https://github.com/tensorflow/tflite-support/compare/master...khanhlvg:migrate-object-detector-to-dataclasses?expand=1

**Comment by kinaryml** [comment]
Since the object detector requires the `Category` class I believe I'll have to update the other classification API as well in the same PR or we'll end up having breaking changes.

**Comment by khanhlvg** [comment]
Thanks Kinar. The overall changes look good. Could you create a PR?

**Comment by kinaryml** [comment]
> Thanks Kinar. The overall changes look good. Could you create a PR?

@khanhlvg I've the raised the PR [here](https://github.com/tensorflow/tflite-support/pull/818).

**Comment by khanhlvg** [comment]
Thanks @kinaryml 
I left some minor comments. PTAL.

**Comment by khanhlvg** [comment]
@kinaryml While the current PR is waiting for internal review, can you create the next two PRs to migrate the Embedder APIs and ImageSegmenter?

**Comment by kinaryml** [comment]
> @kinaryml While the current PR is waiting for internal review, can you create the next two PRs to migrate the Embedder APIs and ImageSegmenter?

@khanhlvg I believe `ColoredLabel` relies on the `Category` dataclass so we should wait till the PR is merged.

**Comment by kinaryml** [comment]
> @kinaryml While the current PR is waiting for internal review, can you create the next two PRs to migrate the Embedder APIs and ImageSegmenter?

Yeah, I'm working on the ImageSegmenter API right now. Will let you know if I come across any issues.

**Comment by kinaryml** [comment]
@khanhlvg Here's the branch with the changes for `ImageSegmenter`. PTAL. Meanwhile, I'll be working on porting the Embedder task APIs.

https://github.com/tensorflow/tflite-support/compare/master...khanhlvg:migrate-image-segmenter-to-dataclasses?expand=1

**Comment by khanhlvg** [comment]
@kinaryml Could you create a PR directly next time? There's no need to share the comparison before creating a PR. Thanks!

**Comment by kinaryml** [comment]
@khanhlvg I've raised a PR for ImageSegmenter her
https://github.com/tensorflow/tflite-support/pull/819

**Comment by khanhlvg** [comment]
@kinaryml Could you sent the next CL to migrate the the Searcher APIs? 

Besides, please send another CL to update the image classifier, object detector and audio classifier tests to define expected result using code rather than text proto similar to the [image_embedder](https://github.com/tensorflow/tflite-support/pull/819/files#diff-9f71f45fa0ad77a7315599c3873e424b5d44c755749f70aeee2c7e3697858d51R38) test. The purpose is to ensure that proto conversion and __eq__ logic are covered in the test.

**Comment by kinaryml** [comment]
@khanhlvg I think the Searcher APIs require the Embedder tasks to be migrated since it happens to make use of embeddings_pb2. I could start working on it as soon as they're merged.

**Comment by kinaryml** [comment]
@khanhlvg I've created a [branch](https://github.com/tensorflow/tflite-support/compare/master...khanhlvg:migrate-searcher-tasks-to-dataclasses?expand=1) with the changes for the Searcher APIs. Although, I'm holding off on sending the PR as the migration for the Embedding tasks hasn't been merged yet. I'll retest the APIs again once the Embedder API PR gets merged.

**Comment by kinaryml** [comment]
@khanhlvg I've raised a PR for the Searcher tasks here.

https://github.com/tensorflow/tflite-support/pull/823/files

**Comment by khanhlvg** [comment]
@kinaryml Thanks Kinar.

The Searcher PR is being reviewed internally. Could you prepare the next PR to migrate BaseOptions to dataclass class? That should be the last PR for this migration work.

**Comment by kinaryml** [comment]
> 

@khanhlvg Yeah, I'll work on it and send a PR once it's ready.

**Comment by kinaryml** [comment]
@khanhlvg I've raised another PR to define the expected result using code instead of the protobuf text proto.
https://github.com/tensorflow/tflite-support/pull/827

**Comment by khanhlvg** [comment]
The migration has been completed. Thanks Kinar!
