### ISSUE TITLE
tflite input

### ISSUE THREAD

**Issue by 1alexuwu** [tensorflow/tflite-support#843]
Hello,

I have no idea how to create the proper array shape for the model input. I tried making a 2D array with dimensions 30x126 and it gives an error saying:

`method TensorBuffer.loadArray(int[]) is not applicable
  (argument mismatch; float[][] cannot be converted to int[])
method TensorBuffer.loadArray(float[]) is not applicable
  (argument mismatch; float[][] cannot be converted to float[])`
  

So, I tried flattening the 2D array to make it one dimensional array. No more errors are displayed, but once I run it, it gave me a runtime error that says, "The size of the array to be loaded does not match the specified shape".

How do I change the input to proper size? The input required has a dimension fit for a 2D array but it won't accept 2D array. I flattened the 2D array but it still says that the shape is wrong. 

P.S. I tried to run the same model in jupyter notebook (the not tflite version) and it works fine, same 30x126 input shape. 

Code: 
`try {
	Alphabet30Frames model = Alphabet30Frames.newInstance(getApplicationContext());

        // Creates inputs for reference.
        TensorBuffer inputFeature0 = TensorBuffer.createFixedSize(new int[]{1, 30, 126}, DataType.FLOAT32);
        TensorBuffer tensorBuffer = TensorBuffer.createDynamic(DataType.FLOAT32);
        tensorBuffer.loadArray(keypointsArray);
        ByteBuffer byteBuffer = tensorBuffer.getBuffer();
        inputFeature0.loadBuffer(byteBuffer);

        // Runs model inference and gets result.
        Alphabet30Frames.Outputs outputs = model.process(inputFeature0);
        TensorBuffer outputFeature0 = outputs.getOutputFeature0AsTensorBuffer();

        // Releases model resources if no longer used.
        model.close();

        System.out.println("Prediction: " + outputFeature0);
} catch (IOException e) {
         // TODO Handle the exception
}`

**Comment by lu-wang-g** [comment]
Assume your model takes a float input tensor with shape [1, 30, 126], you can use the following code to pass in your input data:
```
TensorBuffer inputFeature0 = TensorBuffer.createFixedSize(new int[]{1, 30, 126}, DataType.FLOAT32);

// option 1: use ByteBuffer
FloatBuffer byteBuffer = ByteBuffer.allocateDirect(30*126*4);
byteBuffer.asFloatBuffer().put(<your float array>);
inputFeature0.loadBuffer(byteBuffer);

// option 2: use float[]
float[] floatArr = new float[30*126]; // <-- this needs to be a 1D array.
// Loads your data into floatArr.
inputFeature0.loadArray(floatArr);

Alphabet30Frames.Outputs outputs = model.process(inputFeature0);
```

**Comment by 1alexuwu** [comment]
It worked! Thank you so much! In my case, I flattened my 2D float array to 1D float array first and then used the first option you gave me. Thank youuuu! \^.^/ @lu-wang-g
