### ISSUE TITLE
Rpi3 - could not find a version that satisfies the requirement file tflite-support>=0.4.0

### ISSUE THREAD

**Issue by 0800robin** [tensorflow/tflite-support#858]
I am trying to setup an audio classifier on my Raspberry Pi 3 using this example - https://github.com/tensorflow/examples/tree/master/lite/examples/sound_classification/raspberry_pi 

I have followed the setup steps, however when i run the setup script i run into this error

``` 
Could not find a version that satisfies the requirement tflite-support>=0.4.0 (from -r requirements.txt (line 5)) (from versions: 0.1.0a0.dev3, 0.1.0a0.dev4, 0.1.0a0.dev5, 0.1.0a0, 0.1.0a1)
No matching distribution found for tflite-support>=0.4.0 (from -r requirements.txt (line 5))
```

I am using python 3.7.3 

I have looked into older issues but can't find a resolution
https://github.com/tensorflow/tflite-support/issues/755

Thanks in advance.

**Comment by lu-wang-g** [comment]
@khanhlvg do you mind to take a look at this issue? Many thanks!

**Comment by khanhlvg** [comment]
@0800robin Have you tried updating your pip to the latest version?
`python3 -m pip install pip --upgrade`

then

`python3 -m pip install tflite-support==0.4.0`

If it doesn't work, could you try `python3 -m pip install tflite-support-nightly`?

**Comment by 0800robin** [comment]
Thanks very much @khanhlvg that has solved the issue.

One of the issues was i had mangled my python install a bit but a clean install of raspberry pi OS + updating pip and all is well. 

I can now train a model on Teachable Machine and run it on the Pi. Sweet. 

Thanks again

**Comment by jhabr** [comment]
@khanhlvg This issues seems to have come back.

`pip3 install tflite-support~=0.4.0` was still working perfectly last week (2nd week of January 2023), as per our build server logs:

```
Collecting tflite-support~=0.4.0
  Downloading tflite_support-0.4.3-cp39-cp39-manylinux2014_x86_64.whl (60.9 MB)
```

Now I get the same error as mentioned above:

```
ERROR: Could not find a version that satisfies the requirement tflite-support~=0.4.0 (from versions: 0.1.0a0.dev3, 0.1.0a0.dev4, 0.1.0a0.dev5, 0.1.0a0, 0.1.0a1)
ERROR: No matching distribution found for tflite-support~=0.4.0
```

Nighly build (`tflite-support-nightly`) doesn't seem to be working either.

**Comment by khanhlvg** [comment]
We didn't do any `tflite-support` release since Nov 2022 so I suspect that it's caused by your server upgraded to a newer version of Python that tflite-support isn't supported yet. 
https://pypi.org/project/tflite-support/0.4.3/#files

Please be noted that we only support Python 3.7 - 3.9 at this moment.

**Comment by jhabr** [comment]
Thank you for your response @khanhlvg! You are right, the python version of the server changed to 3.10.x. I wasn't aware that `tflite-support` only supports python 3.7 - 3.9, my bad. Got it fixed.

**Comment by ABDURRAHMANYIGIT** [comment]
@khanhlvg Hi! My python version is 3.7.4 and pip verison is 22.3.1. But when I run
`python -m pip install tflite-support==0.4.0`
I still get this error:
`ERROR: Could not find a version that satisfies the requirement tflite-support==0.4.0 (from versions: 0.1.0a0.dev3, 0.1.0a0.dev4, 0.1.0a0.dev5, 0.1.0a0, 0.1.0a1)
ERROR: No matching distribution found for tflite-support==0.4.0`
I couldn't find the issue could you help me?

**Comment by pedroroutaboul** [comment]
Same Issue here trying with `Python 3.7.16 `

I already tried: 
```
pip install tflite-support-nightly
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
ERROR: Could not find a version that satisfies the requirement tflite-support-nightly (from versions: none)
ERROR: No matching distribution found for tflite-support-nightly
```
```
pip3 install tflite-support~=0.4.0
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
ERROR: Could not find a version that satisfies the requirement tflite-support~=0.4.0 (from versions: 0.1.0a0.dev3, 0.1.0a0.dev4, 0.1.0a0.dev5, 0.1.0a0, 0.1.0a1)
ERROR: No matching distribution found for tflite-support~=0.4.0
```
