### ISSUE TITLE
quantization aware training conversion

### ISSUE THREAD

**Issue by motilal76** [tensorflow/tflite-support#865]
Trying to convert a model with quantization aware training, tensorflow 2.8.2 bombs out 

/usr/local/lib/python3.8/dist-packages/keraslayers/convolutional.py:233 Error 'tf.Conv2D' op is neither a custom op nor a flex op

All i am doing is calling 
'''
     latest = tf.train.latest_checkpoint(checkpoint_dir)
     model.load_weights(latest)
    
    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    quantized_tflite_model = converter.convert()
'''

**Comment by lu-wang-g** [comment]
tf.Conv2D is a very basic op and should be supported in the built-in op. Do you mind to ask the question in the tensorflow/tflite github repo. Our team will help you further from there.
