### ISSUE TITLE
Run audio recognition model on arduino-like board

### ISSUE THREAD

**Issue by Raunak-Singh-Inventor** [tensorflow/tflite-support#867]
How can I run an audio recognition model on an arduino-like board using tflite micro. I can convert it to a model.cc, but I don't know how to run it from there on the microcontroller?

Thanks in advance for your help.

**Comment by lu-wang-g** [comment]
Please ask your question in the tf/tflite github repo [here](https://github.com/tensorflow/tensorflow). The Micro team will help you from there.
