### ISSUE TITLE
ERROR: No matching distribution found for tflite-support-nightly

### ISSUE THREAD

**Issue by akram02** [tensorflow/tflite-support#874]
I am trying to install **tflite-support-nightly** by this command **pip install tflite-support-nightly**.
But it shows this error-
_**ERROR: Could not find a version that satisfies the requirement tflite-support-nightly (from versions: none)
ERROR: No matching distribution found for tflite-support-nightly**_
My operating system is **Ubuntu 22.04 LTS** and my python version is **Python 3.10.4**

**Comment by lu-wang-g** [comment]
Python 10 is not supported at this moment. Please use Python 3.7 ~ 3.9 instead.

Feel free to reopen if you have other questions.
