### ISSUE TITLE
build_pip_package for rpi (elinux_armhf) fails under Docker

### ISSUE THREAD

**Issue by moults31** [tensorflow/tflite-support#879]
I am hitting an error when attempting to cross-compile the tflite-support pip package using the provided Docker container.

# Steps to reproduce:
```
cd tensorflow_lite_support/tools/pip_package/rpi
make docker-build
```
Note that docker-build automatically runs `build_arm_pip_package.sh` which runs the following bazel build commands, which is where the failure occurs
```
bazel build -c opt --config=elinux_armhf --define darwinn_portable=1 --linkopt=-L/usr/lib/arm-linux-gnueabihf tensorflow_lite_support/tools/pip_package:build_pip_package
EXTRA_PKG_NAME_FLAG="--plat-name=manylinux2014-armv7l" ./bazel-bin/tensorflow_lite_support/tools/pip_package/build_pip_package --dst wheels ${NIGHTLY_FLAG}
bazel build -c opt --config=elinux_aarch64 --define darwinn_portable=1 --linkopt=-L/usr/lib/aarch64-linux-gnu tensorflow_lite_support/tools/pip_package:build_pip_package
EXTRA_PKG_NAME_FLAG="--plat-name=manylinux2014-aarch64" ./bazel-bin/tensorflow_lite_support/tools/pip_package/build_pip_package --dst wheels ${NIGHTLY_FLAG}
```

# Error signature:
```
INFO: Analyzed target //tensorflow_lite_support/tools/pip_package:build_pip_package (218 packages loaded, 14328 targets configured).
INFO: Found 1 target...
ERROR: /home/zmoulton/misc/tflite-support/bazel-ci_build-cache/.cache/bazel/_bazel_zmoulton/eab0d61a99b6696edb3d2aff87b585e8/external/XNNPACK/BUILD.bazel:8896:19: Compiling src/qs8-vcvt/gen/vcvt-armv6simd-x8.c failed: (Exit 1): arm-linux-gnueabihf-gcc failed: error executing command /home/zmoulton/misc/tflite-support/bazel-ci_build-cache/.cache/bazel/_bazel_zmoulton/eab0d61a99b6696edb3d2aff87b585e8/external/armhf_linux_toolchain/bin/arm-linux-gnueabihf-gcc -fstack-protector -g0 ... (remaining 85 arguments skipped)
external/XNNPACK/src/qs8-vcvt/gen/vcvt-armv6simd-x8.c: In function 'xnn_qs8_vcvt_ukernel__armv6simd_x8':
external/XNNPACK/src/qs8-vcvt/gen/vcvt-armv6simd-x8.c:26:9: error: unknown type name 'int16x2_t'
   const int16x2_t vminus_input_zero_point = (int16x2_t) params->armv6simd.minus_input_zero_point;
```
Plus many more undefined types that appear to be xnnpack related.

# Notes:
- I am running the docker image on an Ubuntu 22.04 host on an Intel i7 11th gen CPU (x86-64)
- My motivation for cross-compiling from source is to get the change from https://github.com/tensorflow/tflite-support/commit/c478cf68bf9b8254e0a21b52ed3ec3c33979cff8 which I require but is not captured in any release yet. If someone could help me obtain or build a binary containing this fix some other way, that would be an acceptable workaround.

Thanks and let me know if I can provide any more details.

**Comment by lu-wang-g** [comment]
XNNPACK doesn't build well on elinux_armhf. Similar to the TFLite Rpi build, we switched XNNPACK with Ruy. The nightly build has been fixed. See https://pypi.org/project/tflite-support-nightly/0.4.0.dev20221015/#files. You can also try building the Pypi package on your own from source code. Feel free to reopen this issue if you see any further problems.
