### ISSUE TITLE
tflite-support-nightly no longer builds armv7 after 20220816

### ISSUE THREAD

**Issue by moults31** [tensorflow/tflite-support#880]
Hi, I am hoping to get an armv7 pip package containing the fix from this commit: https://github.com/tensorflow/tflite-support/commit/c478cf68bf9b8254e0a21b52ed3ec3c33979cff8. However, it appears that this fix is more recent than the latest proper release, and the nightly builds no longer build arm binaries.

I am requesting one of the following options:
- Could we get armv7 re-added to the nightly builds? OR
- Could we get an ad-hoc armv7 build based on the tip of master? OR
- Could someone point me to how I can build from source (either directly on arm or cross-compile on x86-64)? This is currently blocked for me by https://github.com/tensorflow/tflite-support/issues/879

Thanks!

**Comment by schmidt-sebastian** [comment]
Thanks for pointing this out. I will take a look at our Nightly builds.

**Comment by schmidt-sebastian** [comment]
@moults31 Our nightly pipeline is in a bid of trouble these days since we are mostly focused on MediaPipe Tasks.
We don't want to block you and were wondering what tasks you are interested in?

**Comment by lu-wang-g** [comment]
The nightly build has been fixed. See https://pypi.org/project/tflite-support-nightly/0.4.0.dev20221015/#files. 

I'm closing this issue. Feel free to reopen if needed.
