### ISSUE TITLE
Support for FakeQuantWithMinMaxVarsPerChannel

### ISSUE THREAD

**Issue by manasa12344** [tensorflow/tflite-support#881]
Hello,

I have a Tf1.15 protobuf with the per-channel ops 'FakeQuantWithMinMaxVarsPerChannel', when I try to convert to TFLite, it errors out saying the op is not supported. Will TFLite add support for this op? Thanks!

**Comment by lu-wang-g** [comment]
Please post your question on https://github.com/tensorflow/tensorflow. Our TensorFlow team will help you from there.
