### ISSUE TITLE
No support for tensor image reshape in tflite android sdk from channel first to channel last or vice-versa.

### ISSUE THREAD

**Issue by pucha48** [tensorflow/tflite-support#883]
https://discuss.tensorflow.org/t/how-to-reshape-a-tensor-image-in-android-java-sdk-from-channel-first-to-channel-last/11810
How to reshape a tensor image in android java sdk from channel first to channel last?

**Comment by lu-wang-g** [comment]
Reorder image dimensions like this not supported by TensorImage. TensorImage assumes the underlying buffer has size of [channel, width, height].
