### ISSUE TITLE
TFlite Micro Hello-world continuously restart on ESP32-S3

### ISSUE THREAD

**Issue by priyanshu-makhiyaviya** [tensorflow/tflite-support#884]
@tensorflow/micro

System information

    Host OS Platform and Distribution (e.g., Linux Ubuntu): Ubuntu 18.04
    TensorFlow installed from (source or binary): source
    Tensorflow version (commit SHA if source): 2.3.0
    Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.): ESP32-S3

**Describe the problem**

I am trying to setup the ESP32-S3 for TFlite.
I have compiled TFLite hello-world for ESP32-S3. The compilation got successful but when I flash the image on ESP32-S3, it continuously restarted the board.

Please let me know how can i build and flash TFLite hello-world for ESP32-S3.

**Please provide the exact sequence of commands/steps when you ran into the problem**

Clone the tensorflow repository:
git clone https://github.com/tensorflow/tensorflow.git -b r2.3

Generate the examples The example project can be generated with the following command:
make -f tensorflow/lite/micro/tools/make/Makefile TARGET=esp generate_hello_world_esp_project

Building the example Go the the example project directory:
cd tensorflow/lite/micro/tools/make/gen/esp_xtensa-esp32/prj/hello_world/esp-idf

Set the target: 
idf.py set-target esp32s3

Then build with idf.py:
idf.py build

Flashing an image:
idf.py --port /dev/ttyACM0 flash monitor

But the image when flashed does not work. It keeps restarting.

Any suggestions for this issue?
[cyclic_reboot_ESP32S3.pdf](https://github.com/tensorflow/tflite-support/files/9574262/cyclic_reboot_ESP32S3.pdf)

**Comment by lu-wang-g** [comment]
Please post your question on https://github.com/tensorflow/tensorflow. Our TensorFlow team will help you from there.
