### ISSUE TITLE
iOS Error duplicate symbols for architecture x86_64

### ISSUE THREAD

**Issue by nysamnang** [tensorflow/tflite-support#885]
My project is already integrated with Google MLKit and working as normal. But after installing `pod 'TensorFlowLiteTaskVision'` and run the project again it produced the issue.

<img width="455" alt="Screen Shot 2022-09-22 at 5 04 27 PM" src="https://user-images.githubusercontent.com/28054921/191721305-6d3a8821-9b05-4582-93ab-db096992cc75.png">

I figured out that the code of `GMLImage.h` in `TensorFlowLiteTaskVision Framework` has exactly the same code of `GMLImage.h` in `MLImage Framework`.

**So, my question is how to resolve this problem? or any workaround solution?**

Here is the issue log:

```
duplicate symbol 'OBJC_IVAR$_GMLImage._height' in:
/Users/admin/Documents/Project/my-project/ios/Pods/MLImage/Frameworks/MLImage.framework/MLImage(GMLImage.o)
/Users/admin/Documents/Project/my-project/ios/Pods/TensorFlowLiteTaskVision/Frameworks/TensorFlowLiteTaskVision.framework/TensorFlowLiteTaskVision(GMLImage.o)
duplicate symbol 'OBJC_IVAR$_GMLImage._pixelBuffer' in:
/Users/admin/Documents/Project/my-project/ios/Pods/MLImage/Frameworks/MLImage.framework/MLImage(GMLImage.o)
/Users/admin/Documents/Project/my-project/ios/Pods/TensorFlowLiteTaskVision/Frameworks/TensorFlowLiteTaskVision.framework/TensorFlowLiteTaskVision(GMLImage.o)
duplicate symbol 'OBJC_IVAR$_GMLImage._sampleBuffer' in:
/Users/admin/Documents/Project/my-project/ios/Pods/MLImage/Frameworks/MLImage.framework/MLImage(GMLImage.o)
/Users/admin/Documents/Project/my-project/ios/Pods/TensorFlowLiteTaskVision/Frameworks/TensorFlowLiteTaskVision.framework/TensorFlowLiteTaskVision(GMLImage.o)
duplicate symbol 'OBJC_IVAR$_GMLImage._orientation' in:
/Users/admin/Documents/Project/my-project/ios/Pods/MLImage/Frameworks/MLImage.framework/MLImage(GMLImage.o)
/Users/admin/Documents/Project/my-project/ios/Pods/TensorFlowLiteTaskVision/Frameworks/TensorFlowLiteTaskVision.framework/TensorFlowLiteTaskVision(GMLImage.o)
duplicate symbol 'OBJC_IVAR$_GMLImage._width' in:
/Users/admin/Documents/Project/my-project/ios/Pods/MLImage/Frameworks/MLImage.framework/MLImage(GMLImage.o)
/Users/admin/Documents/Project/my-project/ios/Pods/TensorFlowLiteTaskVision/Frameworks/TensorFlowLiteTaskVision.framework/TensorFlowLiteTaskVision(GMLImage.o)
duplicate symbol 'OBJC_IVAR$_GMLImage._imageSourceType' in:
/Users/admin/Documents/Project/my-project/ios/Pods/MLImage/Frameworks/MLImage.framework/MLImage(GMLImage.o)
/Users/admin/Documents/Project/my-project/ios/Pods/TensorFlowLiteTaskVision/Frameworks/TensorFlowLiteTaskVision.framework/TensorFlowLiteTaskVision(GMLImage.o)
duplicate symbol 'OBJC_IVAR$_GMLImage._image' in:
/Users/admin/Documents/Project/my-project/ios/Pods/MLImage/Frameworks/MLImage.framework/MLImage(GMLImage.o)
/Users/admin/Documents/Project/my-project/ios/Pods/TensorFlowLiteTaskVision/Frameworks/TensorFlowLiteTaskVision.framework/TensorFlowLiteTaskVision(GMLImage.o)
duplicate symbol 'OBJC_CLASS$_GMLImage' in:
/Users/admin/Documents/Project/my-project/ios/Pods/MLImage/Frameworks/MLImage.framework/MLImage(GMLImage.o)
/Users/admin/Documents/Project/my-project/ios/Pods/TensorFlowLiteTaskVision/Frameworks/TensorFlowLiteTaskVision.framework/TensorFlowLiteTaskVision(GMLImage.o)
duplicate symbol 'OBJC_METACLASS$_GMLImage' in:
/Users/admin/Documents/Project/my-project/ios/Pods/MLImage/Frameworks/MLImage.framework/MLImage(GMLImage.o)
/Users/admin/Documents/Project/my-project/ios/Pods/TensorFlowLiteTaskVision/Frameworks/TensorFlowLiteTaskVision.framework/TensorFlowLiteTaskVision(GMLImage.o)
ld: 9 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by lu-wang-g** [comment]
Thanks for flagging the issue! Task Library packs the source code MLImage into our Cocoapods target, that's why you see this duplicated symbols error. We'll depend on the MLImage Cocoapods target in our new release to avoid the conflict.

**Comment by nysamnang** [comment]
That's sounds good!
I hope you will resolve this issues and release a new version very soon 🚀.
Thank you!

**Comment by ewfian** [comment]
Any update?

**Comment by nysamnang** [comment]
No update, one of my app features is still pending 😕

**Comment by lu-wang-g** [comment]
@nysamnang we are addressing this issue through the new MediaPipe Tasks offering. MediaPipe Tasks is the next generation code stack of TFLite Task Library. The iOS API will become available in May. See more details from the site: https://developers.google.com/mediapipe

**Comment by abdelrahman-muntaser** [comment]
Any updates regarding this issue ?.

I am using 

    "react-native": "0.71.8",
    "react-native-reanimated": "^2.17.0",
    "react-native-vision-camera": "^2.15.4",
    "vision-camera-realtime-object-detection": "^0.5.1"
    
  still getting the same issue on ios

**Comment by LaLydi** [comment]
@nysamnang did you manage to solve this issue? I'm having the same problem.

**Comment by nysamnang** [comment]
In my case, I wanted to implement image classification with my custom model. So, I switched from `TensorFlowLiteTaskVision` to `TensorFlowLiteSwift` and was able to achieve what I desired. After that, I did not try to find any other workaround solution or use `MediaPipe`, as suggested by `lu-wang-g`.

I will close this issue as I've identified an alternative solution. If anyone encounters this error, I would appreciate it if you could open a new issue. Thank you!
