### ISSUE TITLE
non-Android Java API support

### ISSUE THREAD

**Issue by SpiReCZ** [tensorflow/tflite-support#889]
I really like Tensorflow Lite and would want to use it on my Java server application (Spring Boot) and Raspberry pi (linux aarch64) or at least in (linux x64).
There is already Java API, but only for Android.

Would it be possible to add support for it (linux - x64, aaarch64)?
(other: macos - x64, arm64; windows x64, arm64)

I know Android is probably the primary focus, but lack of support for classic Java kills it for me and other Java developers/projects that would like to leverage lightweightness of the Tensorflow Lite.

**Having a support for linux aarch64 would allow us to run our applications on Raspberry PI for example.**

Today we are able to use AOT compilation of Java application to produce a native build with small memory footprint. In that case it is beneficial to leverage Tensorflow Lite against Tensorflow.

**Comment by lu-wang-g** [comment]
TFLite doesn't release non-Android Java API on Maven, but you can build one on your own using [tensorflowlite_javalib_stable](https://github.com/tensorflow/tensorflow/blob/106698cce24c0af0fcba3ac412b18f46c3edb0bb/tensorflow/lite/java/BUILD#L373). 

aarch64 and Respberry Pi have been supported. See the instruction here: https://www.tensorflow.org/lite/guide/python.

For further questions, feel free to ask it on https://github.com/tensorflow/tensorflow/issues

**Comment by SpiReCZ** [comment]
Why? It's a standard way of releasing Java libraries. Projects like http://djl.ai/ and whole Java/Kotlin community would benefit from having official builds.
I surely can go and build it, but it lowers the general usage and usability of your efforts.
Unofficial builds won't get community attention either.

**Comment by lu-wang-g** [comment]
Most of the TFLite Java usages today are in Android, that's why we prioritized it more. But feel free to submit a feature request on https://github.com/tensorflow/tensorflow/issues and explain your use case.

**Comment by SpiReCZ** [comment]
The prioritization is understandable, however it reminds me an egg / chicken problem.
Android surely didn't have support as well at some point.
Thanks for answers, i will try my best.
