### ISSUE TITLE
Building from 0.4.2 archive with bazel yields a 0.4.0 whl file

### ISSUE THREAD

**Issue by samuelsont** [tensorflow/tflite-support#890]
I'm trying to build tflite-support 0.4.2 on windows with bazilisk, however, the generated file is `tflite_support-0.4.0-cp310-cp310-win_amd64.whl`. I tried this out a couple times and the results were the same each time: 0.4.0 got generated.

I got everything moving by following the guidance here: https://github.com/tensorflow/tflite-support/issues/755#issuecomment-1060998000 without the nightly flag as that just broke imports.

`./bazel-bin/tensorflow_lite_support/tools/pip_package/build_pip_package --dst wheels`

Could someone please take a look at this?

I'm on Windows 10 using Python 3.10

**Comment by lu-wang-g** [comment]
This is just a version tag issue. The wheel you built actually contains changes for 0.4.2, not just for 0.4.0. 

We've updated the version number though. If you try it later today, you'll find the generated file become `tflite_support-0.4.2-cp310-cp310-win_amd64.whl`
