### ISSUE TITLE
python vision.ImageSegmenter run inference significantly slower than tf.lite.Interpreter

### ISSUE THREAD

**Issue by lillekemiker** [tensorflow/tflite-support#895]
It is already super annoying that the TFLite interpreter for inference on x86 CPU is ridiculously slow.
However, I have found that if running image segmentation with `tf.lite.Interpreter` takes about 2 seconds (and typical UNet model and 256x256x3 px input), then the same inference using `vision.ImageSegmenter` will take almost 4 seconds. That seems crazy to me, since the pre- and post processing done by the `vision.ImageSegmenter` I am also doing manually for the `tf.lite.interpreter` and including in the benchmark.

**Comment by lu-wang-g** [comment]
May you please benchmark ImageSegmenter using the deeplab model and the cat image listed [here](https://github.com/tensorflow/tflite-support/tree/master/tensorflow_lite_support/examples/task/vision/desktop#image-segmenter)? Let me know what the performance metrics are. Thanks.

**Comment by lu-wang-g** [comment]
Closing this issue as there's no updates for months. Feel free to reopen.
