### ISSUE TITLE
Improve build instructions

### ISSUE THREAD

**Issue by joshuahaertel** [tensorflow/tflite-support#905]
I am new to Bazel, however I would like to get this repo set up in order to possibly contribute to it. From a quick search, it seems like building should just be a matter of running something like `bazel build //...`, however I'm getting some issues. The first problem has been centered around this recently added line: https://github.com/tensorflow/tflite-support/blob/15cf9c5fb28fdd4d83302b5118119f578cd7b9d4/tensorflow_lite_support/BUILD#L4

Is that file supposed to include comments like it does in the [tensorflow repo](https://github.com/tensorflow/tensorflow/blob/8f096bf1856ef10fad648e31919bf4e1143ed2d5/tensorflow/BUILD#L39-L41) for some internal tooling at Google or is there something I need to do before trying to build? My current workaround is to just comment out every line that refers to it (about 200 lines so far).

A list of dependencies would be great as well. The Android requirements are clear from the current README, and I love the guide to get it that's currently in the [tools directory](https://github.com/tensorflow/tflite-support/blob/76934e7d3e3444e8f4f7a6c90ee83ebb5c530a36/tensorflow_lite_support/tools/Build_TFLite_Support_Targets.ipynb), (though it would be awesome to expose that in the build instructions). However, I've had to add dependencies as I run into errors, ie. installing clang and adding `CC=clang` to my environment, installing swift, etc. It would be awesome if I knew all the dependencies upfront so, assuming I installed them correctly, I could just run a single build command and have everything working.

I'm currently just running a debian container with bazelisk and fixing issues as I run into them. I'm happy to provide a Dockerfile with what I've done so far so it can be improved and lower the barrier for others hoping to contribute.

**Comment by joshuahaertel** [comment]
One final note, this is my most recent error:
```
ERROR: /workspaces/tflite-support/tensorflow_lite_support/custom_ops/BUILD:21:8: no such package 'testing/base/public': BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package.
```
It feels very similar in nature to the license issue where it seems that there is some internal Google tooling where this line is fine, but open source Bazel doesn't come with as many bells and whistles or something. I just hit it and maybe with some additional searching I can find a sufficient work around. Howerver, it looks complex enough in nature that I figured I should probably just call in the experts at this point :slightly_smiling_face:

**Comment by lu-wang-g** [comment]
The custom_ops/ directory probably doesn't build for a while. I won't bet on it. For the rest of the repo, you can find a colab for building instructions here: https://github.com/tensorflow/tflite-support/blob/master/tensorflow_lite_support/tools/Build_TFLite_Support_Targets.ipynb
