### ISSUE TITLE
Changes to build files cause broken Bazel builds

### ISSUE THREAD

**Issue by Bede-sv** [tensorflow/tflite-support#907]
Commit 15cf9c5fb28fdd4d83302b5118119f578cd7b9d4 seems to have broken Bazel building. 

When trying to build the object_detector_demo using the command in the example file with any commit later than this one, it spits out the following error. Any commit earlier builds fine.

`ERROR: /.../tflite-support/tensorflow_lite_support/examples/task/BUILD:9:15: error loading package 'tensorflow_lite_support': Label '//tools/build_defs/license:license.bzl' is invalid because 'tools/build_defs/license' is not a package; perhaps you meant to put the colon here: '//:tools/build_defs/license/license.bzl'? and referenced by '//tensorflow_lite_support/examples/task:darwinn_portable'
ERROR: /.../tflite-support/tensorflow_lite_support/examples/task/BUILD:9:15: every rule of type config_setting implicitly depends upon the target '//tensorflow_lite_support:license', but this target could not be found because of: error loading package 'tensorflow_lite_support': Label '//tools/build_defs/license:license.bzl' is invalid because 'tools/build_defs/license' is not a package; perhaps you meant to put the colon here: '//:tools/build_defs/license/license.bzl'?
ERROR: /.../tflite-support/tensorflow_lite_support/examples/task/BUILD:9:15: error loading package 'tensorflow_lite_support': Label '//tools/build_defs/license:license.bzl' is invalid because 'tools/build_defs/license' is not a package; perhaps you meant to put the colon here: '//:tools/build_defs/license/license.bzl'? and referenced by '//tensorflow_lite_support/examples/task:darwinn_portable'
ERROR: /.../tflite-support/tensorflow_lite_support/examples/task/vision/desktop/BUILD:35:10: errors encountered resolving select() keys for //tensorflow_lite_support/examples/task/vision/desktop:object_detector_demo
ERROR: Analysis of target '//tensorflow_lite_support/examples/task/vision/desktop:object_detector_demo' failed; build aborted: 
INFO: Elapsed time: 0.207s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (2 packages loaded, 0 targets configured)
FAILED: Build did NOT complete successfully (2 packages loaded, 0 targets configured)
`

**Comment by fergushenderson** [comment]
This is fixed at
https://github.com/tensorflow/tflite-support/commit/cab1598cef35585ea9d8fd037131f08a93de2b16

**Comment by lu-wang-g** [comment]
Thank you Fergus for taking care of it!
