### ISSUE TITLE
Python 3.10 support 

### ISSUE THREAD

**Issue by shonigs** [tensorflow/tflite-support#909]
Hi, could you please add python3.10 support for the python package.
Thanks

**Comment by jmtatsch** [comment]
Especially annoying as python 3.10 seems to have become Ubuntu 22.04 new default python version.

**Comment by kells1986** [comment]
+1 for python 3.10 support

**Comment by lu-wang-g** [comment]
@schmidt-sebastian is looking into this. We'll give update once we have more information.

**Comment by stroudd** [comment]
Hey everyone,

I'm trying to run through [this](https://www.tensorflow.org/lite/models/modify/model_maker/object_detection) example with my own set of image data.  I'm getting the following error:

ERROR: Could not find a version that satisfies the requirement tflite-support>=0.4.2 (from tflite-model-maker) (from versions: 0.1.0a0.dev3, 0.1.0a0.dev4, 0.1.0a0.dev5, 0.1.0a0, 0.1.0a1)
ERROR: No matching distribution found for tflite-support>=0.4.2 (from tflite-model-maker)
ERROR: Could not find a version that satisfies the requirement opencv-python-headless==4.1.2.30 (from versions: 3.4.10.37, 3.4.11.39, 3.4.11.41, 3.4.11.43, 3.4.11.45, 3.4.13.47, 3.4.15.55, 3.4.16.59, 3.4.17.61, 3.4.17.63, 3.4.18.65, 4.3.0.38, 4.4.0.40, 4.4.0.42, 4.4.0.44, 4.4.0.46, 4.5.1.48, 4.5.3.56, 4.5.4.58, 4.5.4.60, 4.5.5.62, 4.5.5.64, 4.6.0.66, 4.7.0.68, 4.7.0.72)
ERROR: No matching distribution found for opencv-python-headless==4.1.2.30

Is this related to this thread, and if so, when will this be supported in 3.10?

thank you!

**Comment by marty90** [comment]
+1

**Comment by schmidt-sebastian** [comment]
We have published Mac and Ubuntu wheels for 3.8, 3.9, 3.10 and 3.11 to our nightly build repo: https://pypi.org/project/tflite-support-nightly/0.4.4.dev20230623/#files
