### ISSUE TITLE
Can't seem to disable logging in Tensorflow-Lite

### ISSUE THREAD

**Issue by petered** [tensorflow/tflite-support#910]
I'm running a tensorflow-lite interpreter in python, and cannot seem to disable logging.  I get a constant stream of messages like: 

```
INFO: FlexDelegate: All tensor shapes are consistent.
WARNING: op 'ReadVariableOp' output0 tensor#7 shape mismatch for  [] != ?
WARNING: FlexDelegate: Some tensor shapes are inconsistent.
INFO: FlexDelegate: All tensor shapes are consistent.
WARNING: op 'PadV2' output0 tensor#13 shape mismatch for  [10] != [?]
WARNING: FlexDelegate: Some tensor shapes are inconsistent.
```

My code for loading and running the model (along with all my attempts to disable logging) is: 

```
def load_tf_boxing_model(path_to_model: str) -> Callable[[BGRImageArray], FrameDetections]:

    tf.get_logger().setLevel('ERROR')
    tf.compat.v1.logging.set_verbosity(tf.compat.v1.logging.ERROR)
    os.environ["GLOG_minloglevel"] = "2"
    os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'  # or any {'0', '1', '2'}

    sig_func = tf.lite.Interpreter(path_to_model).get_signature_runner('image_to_boxes')

    def model_func(bgr_image: BGRImageArray) -> FrameDetections:
        tflite_result = sig_func(input_image = bgr_image)  # THIS LINE GENERATES A TON OF LOG MESSAGES
        id_to_box = tensor_box_detection_dict_to_native_dict(tflite_result)
        return FrameDetections(id_to_box)

    return model_func
```

**Comment by pedromarta** [comment]
Having the same issue, tried all common answers from SO. Were you able to find a solution?

**Comment by MaxAntson** [comment]
Also having this issue, tried everything method from SO and various related issues but no luck. One convoluted way I got rid of it (without removing other console outputs) is via filtering out those lines using grep, e.g. removing any "INFO" and "WARNING" lines. 
`python3 main.py 2> >(grep -vE "(INFO|WARNING)" >&2)`

Worked for my use case but still searching for a much nicer solution.

**Comment by lu-wang-g** [comment]
You'll need to build your custom TFLite binary with logging disabled. See this answer: https://github.com/tensorflow/tensorflow/issues/58050.
