### ISSUE TITLE
Unable to convert tensor flow decision tree, Random forest model into TFlite model

### ISSUE THREAD

**Issue by was-siri-us** [tensorflow/tflite-support#912]
I'm trying to convert a tfdf.keras.RandomForest() model into a Tflite model. But it gives me the following error. How do I convert it into a Tflite model.
![image](https://user-images.githubusercontent.com/116163817/215315374-711d2108-dc83-4f5b-af41-d577e2684d37.png)

**Comment by lu-wang-g** [comment]
Please post this question in the tensorflow repo: https://github.com/tensorflow/tensorflow/tree/master. The TFLite Converter team will help you from there.
