### ISSUE TITLE
android.os.Message memory leak when invoking interpreter.run on latest update of Android 13.

### ISSUE THREAD

**Issue by ml497** [tensorflow/tflite-support#913]
The memory leak can be reproduced on https://github.com/tensorflow/examples/tree/master/lite/examples/pose_estimation/android

It seems to affect only the latest update of Android 13.

This is after running the example for roughly 20 minutes:

![tfliteleak](https://user-images.githubusercontent.com/6312560/216818859-726c7360-69f7-4770-a3c4-fa1ae4e0b1ee.png)

**Comment by lu-wang-g** [comment]
Please fill a bug in the tensorflow repo: https://github.com/tensorflow/tensorflow/tree/master/. TFLite team can further assist you from there.
