### ISSUE TITLE
Support for protobuf 4.x ?

### ISSUE THREAD

**Issue by fabien-corso** [tensorflow/tflite-support#914]
Hi,

I am currently running tflite-support python cojointly with grpc which last versions use protobuf > 4.x.
Current version of tflite-support depends on an older version of protobuf, not compatible.

Are there any plan to support protobuf > 4.x for tflite-support ?
On the other hand, are there some instructions somewhere to self build the python pip package ?

Thank you in advance and for this great lib.

**Comment by lu-wang-g** [comment]
There's no plan to to upgrade to protobuf 4.0 in the near future. 

For instruction to build TFLite Support Pypi, see it here: https://github.com/tensorflow/tflite-support/issues/755#issuecomment-1060998000.
