### ISSUE TITLE
How to fill or provide input tensor while inferencing in cpp.

### ISSUE THREAD

**Issue by sagar1899** [tensorflow/tflite-support#915]
i'm using memcpy like below.

memcpy(interpreter->typed_input_tensor<float>(0), frame.data, frame.step[0] * frame.rows);
frame is numpy array got using opencv imread.

at run time i'm getting Segmentation fault (core dumped) error.

also used vector instead of numpy array like below.

memcpy(interpreter->typed_input_tensor<int>(0), myvec, sizeof(myvec));
myvec is vector. but got the same error.

**Comment by fergushenderson** [comment]
You need to call AllocateTensors() first.
Can you try calling interpreter->AllocateTensors() before calling interpreter->typed_input_tensor(0)?

**Comment by lu-wang-g** [comment]
Closing this issue as there's no response for a while. Feel free to reopen.
