### ISSUE TITLE
Could not find a version that satisfies the requirement tflite-support==0.4.2

### ISSUE THREAD

**Issue by pedroroutaboul** [tensorflow/tflite-support#917]
When I run `pip install tflite-support==0.4.2` on Python 3.7.16 
I get 
```
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
ERROR: Could not find a version that satisfies the requirement tflite-support==0.4.2 (from versions: 0.1.0a0.dev3, 0.1.0a0.dev4, 0.1.0a0.dev5, 0.1.0a0, 0.1.0a1)
ERROR: No matching distribution found for tflite-support==0.4.2
```

This look like a recurrent issue https://github.com/tensorflow/tflite-support/issues/858

**Comment by lu-wang-g** [comment]
Here is the all the built variants we supported for 0.4.2: https://pypi.org/project/tflite-support/0.4.2/#files. Please check if your system setup is one of them.

**Comment by lu-wang-g** [comment]
May you try updating your pip first by `python3 -m pip install pip --upgrade`?

**Comment by pedroroutaboul** [comment]
Yes, actually, the setup.py is running that command https://github.com/tensorflow/examples/blob/master/lite/examples/object_detection/raspberry_pi/setup.sh#L10

**Comment by MaxBoyman** [comment]
I'm having same problem. why it is not being fixed even after 2 updates? 
I'm on ubuntu 22.04 and python version 3.9.16. still having the error:
ERROR: Could not find a version that satisfies the requirement tflite-support>=0.4.2 (from versions: 0.1.0a0.dev3, 0.1.0a0.dev4, 0.1.0a0.dev5, 0.1.0a0, 0.1.0a1)
ERROR: No matching distribution found for tflite-support>=0.4.2
pip version is 23.1.1 setuptools 67.7.1 wheel 0.40.0
how can we fix this?

**Comment by MaxBoyman** [comment]
It seems that the the only way to install tf module maker is to do it on ubuntu <=22.04 with python 3.8. and everything else not working. even building tflite with bezel is much more complicated and a lot of errors shows up with different results and sources.

**Comment by lu-wang-g** [comment]
We've finished the majority migration work from TFLite Task Library to MediaPipe. If you continue seeing issues with the tflite-support Pypi package, try using MediaPipe Task (https://developers.google.com/mediapipe/solutions/tasks#python) as an alternative. TFLite Model Maker has also been upgraded in MediaPipe. See more details about MediaPipe Model Maker [here](https://developers.google.com/mediapipe/solutions/model_maker).

**Comment by Chebulex** [comment]
Have the same as issue as kravcc
MacBook Pro 2019
Intel i7
Python 3.11 but tried downgrading on 3.9.16 like kravcc, didn't help, though
pip 23.1.2

I tried it locally, since the whole [Google Colab this](https://www.tensorflow.org/lite/models/modify/model_maker/image_classification) does not work - the Colab keeps downloading tons of data for tflite-model-maker and the virtual machines of Colab don't provide enough space.

**Comment by matheusschreiber** [comment]
Same issue any updates?

Log:

ERROR: Could not find a version that satisfies the requirement tflite-support>=0.4.2 (from tflite-model-maker) (from versions: 0.1.0a0.dev3, 0.1.0a0.dev4, 0.1.0a0.dev5, 0.1.0a0, 0.1.0a1)
ERROR: No matching distribution found for tflite-support>=0.4.2 (from tflite-model-maker)
ERROR: Could not find a version that satisfies the requirement opencv-python-headless==4.1.2.30 (from versions: 3.4.10.37, 3.4.11.39, 3.4.11.41, 3.4.11.43, 3.4.11.45, 3.4.13.47, 3.4.15.55, 3.4.16.59, 3.4.17.61, 3.4.17.63, 3.4.18.65, 4.3.0.38, 4.4.0.40, 4.4.0.42, 4.4.0.44, 4.4.0.46, 4.5.1.48, 4.5.3.56, 4.5.4.58, 4.5.4.60, 4.5.5.62, 4.5.5.64, 4.6.0.66, 4.7.0.68, 4.7.0.72)
ERROR: No matching distribution found for opencv-python-headless==4.1.2.30

**Comment by schmidt-sebastian** [comment]
We have published Mac and Ubuntu wheels for 3.9, 3.10 and 3.11 to our nightly build repo: https://pypi.org/project/tflite-support-nightly/0.4.4.dev20230623/#files

**Comment by kelvinwatson** [comment]
Has this ever been resolved?

MacOS 13.5.1
Python 3.9.6
pip 23.3.1

```
git clone https://github.com/tensorflow/examples
cd examples/tensorflow_examples/lite/model_maker/pip_package
pip install -e .
```
```
ERROR: Could not find a version that satisfies the requirement tflite-support>=0.4.2 (from tflite-model-maker) (from versions: 0.1.0a0.dev3, 0.1.0a0.dev4, 0.1.0a0.dev5, 0.1.0a0, 0.1.0a1)
ERROR: No matching distribution found for tflite-support>=0.4.2
```

**Comment by Albert240507** [comment]
I don't understand why the same error keeps appearing over and over again with different versions of Python, pip, etc.

Right now, I'm getting the same error:

 
```
C:\pip install tflite-runtime
ERROR: Could not find a version that satisfies the requirement tflite-runtime (from versions: none)
ERROR: No matching distribution found for tflite-runtime
```
My current version of Python is :

`Python version: Python 3.10.0`

pip version: Initially 21.3.1, but updated to 25.0.1


```
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pip in c:\users\admin\appdata\roaming\python\python310\site-packages (25.0.1)
```


I'm currently on Windows 11, but I also need it for Ubuntu 24.01 or a Docker container running that version of Ubuntu.

Any help, please?
