### ISSUE TITLE
Tensorflow Lite library is crashing in WASM library at 3rd inference

### ISSUE THREAD

**Issue by L1onKing** [tensorflow/tflite-support#920]
I have C++ code that I want to deploy as WASM library and this code contains TFLite library. I have compiled TFLite library with XNNPack support using Emscripten toolchain quite easy, so no issue there. I have a leight-weight convolution+dense model that runs perfectly on Desktop, but I am starting having problems in the browser.

In 99% of cases I have an error on the third inference:

`Uncaught RuntimeError: memory access out of bounds`

Through some trivial debugging I have found out that the issue comes from `_interpreter->Invoke()` method. Does not matter if I put any input or not, I just need to call Invoke() three times and I have a crash.

First thing first: I decided to add more memory to my WASM library by adding this line to CMake:

`SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -s TOTAL_STACK=134217728 -s TOTAL_MEMORY=268435456")`
`SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -s ALLOW_MEMORY_GROWTH=1")`
128 MB and 256 MB in total for 1 MB model - I think this is more than enough. And on top of that, I am allowing Memory Growth. But unfortunately, I have exactly the same issue.

I am beating on this problem for 2 weeks straight and at this stage I have no clue how to fix it. Also I have tried to set custom allocation using `TfLiteCustomAllocation` but in this case I have a crash on the very first inference, although code works on Desktop flawlessly as well. I guess I was not using it right for WASM specifically, but unfortunately I couldn't find even one tutorial describing how to apply custom allocation in TFLite.

I said that I have a crash in 99% of cases. There was one time when WASM library worked and inference worked as well. It happens just randomly once, and I couldn't reproduce it anymore.

Please give me any advise on how to tackle this issue further. Thanks!

**Comment by lu-wang-g** [comment]
Running a TFLite model on Web is supported by this WASM library of TFLite Interpreter: https://js.tensorflow.org/api_tflite/0.0.1-alpha.4/. Please check it out.
