### ISSUE TITLE
ModuleNotFoundError: No module named 'tflite_micro'

### ISSUE THREAD

**Issue by cannnnnnnnnnnn** [tensorflow/tflite-support#937]
![image](https://github.com/tensorflow/tflite-support/assets/62045849/be504a5c-6afc-46ba-8a24-e11cfc115b8a)

**Comment by cannnnnnnnnnnn** [comment]
I did not find the solution and did not find the package while using conda and pip commands

**Comment by justingrammens** [comment]
I've run into this same issue. Using MacOS Ventura 13.5.1. Python 3

% uname -a
Darwin justins-mbp.lan 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:21:56 PDT 2023; root:xnu-8796.141.3~6/RELEASE_X86_64 x86_64

**Comment by ParanoidDeamer** [comment]
Did you solve this problem？
