### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement tflite-support==0.4.4

### ISSUE THREAD

**Issue by CheesyFrappe** [tensorflow/tflite-support#959]
I’m trying to import tflite-support.task on Raspberry Pi 4. 
When I look at the [requirements file](https://github.com/tensorflow/examples/blob/master/lite/examples/object_detection/raspberry_pi/requirements.txt), it says `tflite-support` above than `0.4.2`.

When I try to install the tflite-support dependency via pip:
`python -m pip install --upgrade tflite-support==0.4.4`

the output is:
`ERROR: Could not find a version that satisfies the requirement tflite-support==0.4.4 (from versions: 0.1.0a0.dev3, 0.1.0a0.dev4, 0.1.0a0.dev5, 0.1.0a0, 0.1.0a1) ERROR: No matching distribution found for tflite-support==0.4.4`

The Python version I'm using is 3.11.2. Would there be any workarounds or fixes to try?

**Comment by likeconan** [comment]
Same issue, it did not work on 3.11.2

**Comment by CheesyFrappe** [comment]
@khanhlvg do you mind taking a look at this issue? Many thanks.

**Comment by soumya997** [comment]
Hi @khanhlvg any update on this issue?

**Comment by CheesyFrappe** [comment]
I think I resolved the issue. I was looking around the other issues in the repository and came across #858. Here's what @khanhlvg commented on the issue:
"Please be noted that we only support Python 3.7 - 3.9 at this moment."

The latest Raspberry Pi OS (Bookworm) comes with Python 3.11. So I switched to Bullseye, which comes with 3.9 as default, and it worked along with the other modules in the [requirements file](https://github.com/tensorflow/examples/blob/master/lite/examples/object_detection/raspberry_pi/requirements.txt). 

I recommend you to try the earliest versions of Python. Seems like `tflite-support` will not support Python 3.11 in the near future.
